### ISSUE TITLE
5 May 12:00 - 23:59 parsed wrong

### ISSUE THREAD

**Issue by BtM909** [wanasit/chrono#102]
Apologies, as I couldn't it test yet with the latest release, but it also doesn't work on the demo page http://wanasit.github.io/pages/chrono/.

It seems like it's doing something with the 12 and therefore ignoring the 5. It also doesn't work when you use '5 May 12:00'.

This works:
May 5 12:00
5 of May 12:00
5th May 12:00
5th of May 12:00

Is it possible to recognize 5 May as well?

Thanks

**Comment by penne12** [comment]
It's trying to parse American English in your example.

**Comment by BtM909** [comment]
That might be the issue, but I would say the problem isn't the American English parser. 

When you use a single digit for the hours it is working... There has been different behavior in the past with single and double digits for hours.

So:

5 May 1:00 
until
5 May 9:59:59 works :P

**Comment by penne12** [comment]
Oh! So chrono is probably giving priority to the date like so:

[5 May] [1:00]
7 [May 1][1:00]

Looks like there is no word boundary in the regexp after the date for the American date parser?

**Comment by wanasit** [comment]
Fixed in 8b76eb3
