### ISSUE TITLE
npm release for version 1.2.0

### ISSUE THREAD

**Issue by chuym** [wanasit/chrono#103]
It's currently not possible to install `chrono-node` to version 1.2.0 with npm.

Any chance to push a new version to npm soon?

**Comment by penne12** [comment]
@wanasit, I'm not an authorized user for npm - can you please do this?

**Comment by wanasit** [comment]
I published the new version in npm. I didn't notice that we have tag version `v1.2.0`, as the new version should still be `1.1.7`. This should fix the problem in #106 too
