### ISSUE TITLE
When parsing leading zero 24h time (00:00 - 09:00) meridiem is not certain

### ISSUE THREAD

**Issue by jonotron** [wanasit/chrono#109]
```javascript
chrono.parse('09:00')[0].start.isCertain('meridiem') // false
chrono.parse('10:00')[0].start.isCertain('meridiem') // false
chrono.parse('11:00')[0].start.isCertain('meridiem') // false
chrono.parse('12:00')[0].start.isCertain('meridiem') // false
chrono.parse('13:00')[0].start.isCertain('meridiem') // true
```

24h time with leading zeros (00:00 - 09:00) do not have a meridiem that is certain, times 13:00-23:00 have certain meridiems.

Is this expected behaviour or should times with leading zeros have meridiem assigned/certain?

I understand the ambiguity of 10:00-12:00 and it would not be possible to be certain of meridiem in those hours.

**Comment by penne12** [comment]
I think that 01:00 is probably 1 AM, but it's not certain. I think it's expected behavior for the meridiem to not be certain there, but your example should still default to AM, just without being certain.

**Comment by jonotron** [comment]
Yes, you are correct. 01:00 does return 1am with meridiem uncertain. Thanks for clarifying the expectation on this.
