### ISSUE TITLE
'To date' not understood

### ISSUE THREAD

**Issue by jordanfinners** [wanasit/chrono#112]
The phrases month to date, year to date are not understood and return null.

**Comment by wanasit** [comment]
Hi, could you please be more specific about the bug?
eg. what was your input text?, and what was your expected output?

**Comment by jordanfinners** [comment]
Hi, 
Yes so for instance 'In the month to date' or 'In the year to date', where I would expect the output to be the start or the month or year respectively.

**Comment by penne12** [comment]
@jordanfinners I'm closing until you provide some more complete examples. For example:

> `tmr at 5` should return `Sun Oct 16 2016 05:00:00 GMT-0500 (CDT)`.

**Comment by jordanfinners** [comment]
Hello,
So todays date is the 15th November 2016, just for reference in the examples.

**Examples**

`in the year to date` should return `Fri Jan 01 2016 00:00:00 GMT+0000 (GMT Standard Time)`
`in the month to date` should return `Tue Nov 01 2016 00:00:00 GMT+0000 (GMT Standard Time)`
