### ISSUE TITLE
'in 3 months', 'three months ago' are not understood by chrono

### ISSUE THREAD

**Issue by anqitong** [wanasit/chrono#113]
- 'in 3 days' works, but 'in three days' does not work
- 'in 3 months' does not work
- '3 months ago' works but 'three months ago' does not work

**Comment by Themandunord** [comment]
Hello @wanasit,
I've you got an idea ? I'm interested on it too.

**Comment by wanasit** [comment]
Fixed in 1b16391 and 6fe02b344b7960c6ab6d1d959638dc2a93de1026
Try chrono version 1.2.2+

**Comment by thingista** [comment]
Hopefully it has not been discussed elsewhere (I could not find it) but is it by "choice" that things like
`last month`
`last week`
do not work (whereas `last friday` or` one month ago` do) or is it a current limitation?
