### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by SemihAkar** [wanasit/chrono#114]
Hey,

Is it possible to set timezone for parsing? For example, when I said 'tonight', it returns the 22:00PM according to server's time zone. But I want it to return according to a given timezone. I have tried to give refence date with timezone but it didnt change the result. How can I do that?

**Comment by wanasit** [comment]
hmm. how about just assign the timezone offset in the result?
```
var result = chrono.parse('today');
// result.start.date() = Mon May 02 2016 12:00:00 GMT+0900 (JST)

result.start.assign('timezoneOffset', -420) // PDT -0700
// result.start.date() = Tue May 03 2016 04:00:00 GMT+0900 (JST)
```

**Comment by SemihAkar** [comment]
It does not solve the problem.

Lets say I live in +03 time zone. When I said 'tonight', it means 22:00GMT+03 (which equals in UTC 19:00Z). But If I live in +05 time zone, and I say 'tonight' it means 22:00GMT+05 (which equals in UTC 17:00Z). Therefore results are different timestamps and I cannot fix it by setting offset value. (setting offset value just changes the format actually).

**Comment by SemihAkar** [comment]
That works. I understood your solution after I looked into the code. Thanks for it :)
