### ISSUE TITLE
Sunday night 7th June 2015 returns coming sunday

### ISSUE THREAD

**Issue by krazylearner** [wanasit/chrono#117]
Hi 
I used http://wanasit.github.io/pages/chrono/ to parse a query like this "Sunday night 7th June 2015"

and i got "Sun May 15 2016 12:00:00 GMT+0530 (India Standard Time)" as returned value .

can you please check it ?

**Comment by wanasit** [comment]
Hi. Sorry for my slow response.

The parse on "Sunday night 7th June 2015" currently returns two results, "Sunday" and "7th June 2015".
```
chrono.parse('Sunday night 7th June 2015')

chrono.parse('Sunday night 7th June 2015')[0].start.date()
// Sun Jun 12 2016 12:00:00 GMT+0900 (JST)

chrono.parse('Sunday night 7th June 2015')[1].start.date()
// Sun Jun 07 2015 12:00:00 GMT+0900 (JST)
```

It is more difficult to make Chrono recognize them as the same day during the "night". I don't I can make it happen soon.

**Comment by penne12** [comment]
In this scenario, it makes sense, but in some cases, like the following, this could mess up in casual language. For example:

> Hey dude, could you come over for dinner Sunday night 7th June 2015 or next Friday?

or, which is possible but hard to account for

> Hey dude, could you meet me for lunch Friday night 7th June 2015 or next Saturday?

Your described scenario seems less likely than the one I mentioned above, plus, joining the two would require significant changes that make little sense to implement considering the small benefit compared to the time cost and potential problems. 

Feel free to submit a PR if you have an idea of how to work around this, but I'm closing for now.
