### ISSUE TITLE
AND / OR and TO / THROUGH conditions returns dates in the past

### ISSUE THREAD

**Issue by stroupaloop** [wanasit/chrono#118]
For example: Monday to Friday (current date is May 15th)

Returns with

    start.date() > May 13th (last Friday)
    stop.date() > May 16th (this coming Monday)

but should instead return

    start.date() > May 16th (this coming Monday)
    stop.date() > May 20th (this coming Friday)

**Comment by gregeinfrank** [comment]
This should use `forwardDatesOnly` option to toggle on/off.

**Comment by stroupaloop** [comment]
Awesome, can you provide an example for how that's used or set when parsing
a date/time? Thanks!

On Tue, May 17, 2016 at 8:30 PM, Gregory Einfrank <notifications@github.com>
wrote:

> This should use forwardDatesOnly option to toggle on/off.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/wanasit/chrono/issues/118#issuecomment-219893677>
>



-- 
"And that's why you always leave a note"
http://stroupaloop.com
<https://mailtrack.io/trace/link/5cc21925fb82e119a340eb6427e1c95365c17d9d?url=http%3A%2F%2Fstroupaloop.com&signature=f0749d97420bd840>

**Comment by nbikar** [comment]
This does not seem to solve my problem. Most probably "this"is misleading.  Today is Thursday, Aug 4th

var inputText = "this Friday to this Monday";
var parsedTime = chrono.parse(inputText, new Date(), {forwardDateOnly: true});

Returns with

start.date() > Aug 1st (last Monday)
end.date() > Aug 5th (this Friday (tomorrow))

but should instead return

start.date() > Aug 5th (this coming Monday)
end.date() > Aug 8th (this coming Friday)

**Comment by wanasit** [comment]
Fixed in a34235a.
