### ISSUE TITLE
jsDelivr 1.2

### ISSUE THREAD

**Issue by skeggse** [wanasit/chrono#119]
It looks like jsDelivr still isn't delivering the current version of the library for [1.2.0](https://cdn.jsdelivr.net/chrono/1.2.0/chrono.min.js). In particular, `now` still doesn't work: `new chrono.Chrono().parseDate('now')` returns `null`.

See also #78, #103, #106, jsdelivr/jsdelivr#8750

**Comment by bradvogel** [comment]
print @wanasit

**Comment by wanasit** [comment]
Sorry for my super slow response.
I've push a new tag (v1.2.3) to the repo. You should try pull the new [1.2](https://cdn.jsdelivr.net/chrono/1.2/chrono.min.js) from jsDelivr
