### ISSUE TITLE
Result format

### ISSUE THREAD

**Issue by soyjavi** [wanasit/chrono#120]
Hi,

IMHO, the response format (ex. `Thu Jun 02 2016 12:00:00 GMT+0700 (ICT)`) is not friendly with another common libraries (ex. `moment`). What you think about choose the response format? (ex. Native `Date` value or an specific `string`)

Best,

**Comment by wanasit** [comment]
Hi. Sorry for my slow response.

I'm not sure "response format" you were talking about. chrono.parseDate() returns native Javascript Date object. chrono.parse() return a list of ParsedResult objects, which you can still get start and end in native js.
```
var parseResult = chrono.parse('today')[0]
var startDate = parseResult.start.date(); 
// startDate is native javascript Date object
// Try startDate.getTime()
```

**Comment by soyjavi** [comment]
Thanks guy!!! I wonder I did something wrong... now it's working.

By the way, thanks for this library.
