### ISSUE TITLE
Saturday and next Saturday parsing incorrectly

### ISSUE THREAD

**Issue by jessecurry** [wanasit/chrono#121]
It appears that "Saturday" and "next Saturday" are not interpreted correctly.

Here are strings that I have tried and the results:

- Today at 11:30 AM -> June 13th, 2016 @ 11:30 AM
- Saturday at 11:30 AM -> June 11th, 2016 @ 11:30 AM
- next Saturday at 11:30 AM -> June 25th, 2016 @ 11:30 AM

I'd expect that "Saturday" and "next Saturday" would return June 18th. I'm using Safari on Mac OS X.

**Comment by wanasit** [comment]
"This Saturday" is not equal "Saturday". 
```javascript
var refDate = new Date(2016, 6-1, 13, 11, 30);
chrono.parseDate('Saturday', refDate)         // Sat Jun 11 2016
chrono.parseDate('this Saturday', refDate)  // Sat Jun 18 2016 
chrono.parseDate('next Saturday', refDate) // Sat Jun 25 2016 
```

Currently, if the input is just "Saturday" without any other information, Chrono will find the closest Saturday as it is the most likely (e.g. "I watched movie on Saturday" or "I'm going to watch movie on (this) Saturday").

I would not change this behavior for now.

**Comment by jessecurry** [comment]
Is there any flag that can force all parsed dates into the future?

**Comment by wanasit** [comment]
Hmm. Not really. You need to write some code. There was a similar case like this in the past.
https://github.com/wanasit/chrono/issues/19
