### ISSUE TITLE
Chrono does not understand "in 10 Days"

### ISSUE THREAD

**Issue by mgilson** [wanasit/chrono#124]
Chrono will correctly parse `"in 10 days"`, but it does not correctly parse `"in 10 Days"`.  I believe that even though the following [regular expressions are case insensitive](https://github.com/wanasit/chrono/blob/master/src/parsers/EN/ENDeadlineFormatParser.js#L11-L23), subsequent tests for further parsing [only match lower case](https://github.com/wanasit/chrono/blob/master/src/parsers/EN/ENDeadlineFormatParser.js#L58).

**Comment by wanasit** [comment]
Thank you for reporting the problem. Fixed in 6b97e73.
