### ISSUE TITLE
Custom Chrono with Refiner No Longer Parses Date

### ISSUE THREAD

**Issue by xd1936** [wanasit/chrono#125]
In [the Chrono readme for refiners](https://github.com/wanasit/chrono/blob/master/README.md#refiner), you talk about making a custom `chrono[]` object that you add a refiner to. When you follow that tutorial exactly, then your custom Chrono no longer parses the date! Just the time! What's up with that?

**Comment by xd1936** [comment]
I'm trying to make Chrono bias meridiems to be during the workday, which would be a pretty similar task to your example in the tutorial. Something like

```
var workdayChronoBuilder = new chrono.Refiner();
workdayChronoBuilder.refine = function(text, results, opt) {
  // If there is no AM/PM (meridiem) specified, 
  // let all time between 1:00 - 7:00 be PM (13.00 - 19.00)
  results.forEach(function (result) {
    if (!result.start.isCertain('meridiem') &&
        result.start.get('hour') >= 1 && result.start.get('hour') < 7) {
      result.start.assign('meridiem', 1);
      result.start.assign('hour', result.start.get('hour') + 12);
    }
  });
  return results;
}
var workdayChrono = new chrono.Chrono();
workdayChrono.refiners.push(workdayChronoBuilder);
```

With this (being parsed today, 6/28/2016),
`chrono.parseDate("tomorrow at 3") // Wed Jun 29 2016 03:00:00 GMT-0400 (EDT)`
`workdayChrono.parseDate("tomorrow at 3") // Tue Jun 28 2016 15:00:00 GMT-0400 (EDT)`
`workdayChrono.parseDate("yesterday at 3") // Tue Jun 28 2016 15:00:00 GMT-0400 (EDT)`
`workdayChrono.parseDate("saturday at 3") // Tue Jun 28 2016 15:00:00 GMT-0400 (EDT)`
`workdayChrono.parseDate("next week at 3") // Tue Jun 28 2016 15:00:00 GMT-0400 (EDT)`
`workdayChrono.parseDate("8/1/2016 at 3") // Mon Aug 01 2016 15:00:00 GMT-0400 (EDT)`

Time is right, date is not. Pretty weird.

**Comment by wanasit** [comment]
There is a parameter for Chrono option (e.g. 'casual' vs 'strict'), and the default option is 'strict' mode which won't accept 'next week', 'Saturday', etc.

Just update your code like this should make it works.
```
var workdayChrono = new chrono.Chrono(chrono.options.casualOption());
workdayChrono.refiners.push(workdayChronoBuilder);
```
I'm updating document and example now.
