### ISSUE TITLE
[Feature request] Hours in the future

### ISSUE THREAD

**Issue by gmarty** [wanasit/chrono#127]
That'd be good to have a mode to force chrono to always return dates in the future.
With this mode on, expressions like 'on Saturday' will refer to the next Saturday, not the previous one.
Likewise, 'at 5 today' will refer to '5pm' if the current time is after 5am.

**Comment by gregeinfrank** [comment]
@gmarty you can pass in the option `forwardDatesOnly`. See PR here: https://github.com/wanasit/chrono/pull/82/files

**Comment by gmarty** [comment]
Yes, I saw that but it only works for dates. I've updated the title of this issue.
Anyway, I solved it with the following refiner:
```js
const forwardHoursRefiner = new chrono.Refiner();
forwardHoursRefiner.refine = (text, results, opt = {}) => {
  if (opt.forwardHoursOnly !== true) {
    return results;
  }

  // If the date is today and there is no AM/PM (meridiem) specified,
  // let all the time be after the current time.
  results.forEach((result) => {
    changeDate(result.start, result.ref);
    if (result.end) {
      changeDate(result.end, result.ref);
    }
  });

  return results;

  function changeDate(component, ref) {
    if (!component.isCertain('meridiem')
      && component.get('year') === ref.getFullYear()
      && component.get('month') === ref.getMonth() + 1
      && component.get('day') === ref.getDate()
      && component.get('hour') < ref.getHours()) {
      component.assign('meridiem', 1);
      component.assign('hour', component.get('hour') + 12);
    }
  }
};
```

I may clean it, write tests and submit a patch if somebody else is interested.

**Comment by penne12** [comment]
@gmarty Looks great! I'd love to see a PR.
