### ISSUE TITLE
The word "before" splits dates

### ISSUE THREAD

**Issue by mdemblani** [wanasit/chrono#128]
I have been using ChronoJs for quite some time and recently encountered a problem. I entered the following string : 

**_Do something tomorrow before 4pm_** 

My expectation was that it would return me a proper date and time object, with the date being that of the next day and time being 4pm. But it did not behave as required. In the returned value, date part was correctly returned, but the time part returned midnight.

For example:

Consider right now is 
21 July 2016, 3:30 pm

Expected Result:  Fri Jul 22 2016 16:00:00
Returned Result: Fri Jul 22 2016 12:00:00

_I have exclued the timezone part from the string just for the sake of simplicity_

**Comment by penne12** [comment]
Looks like the word `before` is separating the dates. @wanasit, what would be the best path forward with this?

**Comment by wanasit** [comment]
In this case, `before` work like `at`. We should update the separation pattern to recognize `before` too.

**Comment by penne12** [comment]
I can take a look at this tomorrow.

**Comment by wanasit** [comment]
I've already fixed this in 5406f2a, but thanks Ben.

**Comment by penne12** [comment]
@wanasit Awesome.
