### ISSUE TITLE
Support for weeks

### ISSUE THREAD

**Issue by gczh** [wanasit/chrono#13]
There should be support for weeks. Some test cases:

**Current date:** 9th August 2013

1. **1 week later:** 16 August 2013
2. **in 1 week:** 16 August 2013
3. **next week:** 16 August 2013

**Comment by manakor** [comment]
I am also wondering how do we process on such a formats, often used by people when mentioning next week. This ones are pretty obvious will mean exact date next week:
 - on Tuesday, next week
 - Friday, next week

**Comment by wanasit** [comment]
@manakor I've updated the weekday parser to handle postfix 'last week', 'next week', etc in this commit 0a38c6653240dcdcaa116e7febe2d2b4f11917a5.

**Comment by penne12** [comment]
**Awesome!**

**Comment by thomasfoster96** [comment]
For what it's worth, if I read something that referred to "last week" I would assume it referred to the seven days ending last sunday. On the other hand, "Thursday last week" would be referring to last Thursday.

Deciding whether "at our meeting last week" refers to seven days ago or to the whole of the last week seems a little out of the scope of this library to be honest.

**Comment by penne12** [comment]
How about make this optional? If you want to enable it, you can add the parser (bundled with chrono)

**Comment by gagan-bansal** [comment]
Is there support for "weekend"? 
Examples:
- coming weekend
- last weekend
- this weekend
- next weekend

It would be nice if we have support for weekend.
