### ISSUE TITLE
Keyword "morning" is not identified

### ISSUE THREAD

**Issue by tlindener** [wanasit/chrono#133]
Hi,

I have the following string "how is the weather in hamburg on Monday between morning and noon?"

I expected a result list, were Monday, morning and noon would have been spotted, but actually only Monday and noon are identified. 
This is the result:
```
  "chrono_default": [{
            "ref": "2016-08-11T09:55:36.266Z",
            "index": 33,
            "text": "Monday",
            "tags": {},
            "start": {
                "knownValues": {
                    "weekday": 1
                },
                "impliedValues": {
                    "day": 8,
                    "month": 8,
                    "year": 2016,
                    "hour": 12,
                    "minute": 0,
                    "second": 0,
                    "millisecond": 0
                }
            }
        }, {
            "ref": "2016-08-11T09:55:36.266Z",
            "index": 60,
            "text": "noon",
            "tags": {
                "ENTimeExpressionParser": true
            },
            "start": {
                "knownValues": {
                    "hour": 12,
                    "minute": 0,
                    "meridiem": 1
                },
                "impliedValues": {
                    "second": 0,
                    "millisecond": 0,
                    "day": 11,
                    "month": 8,
                    "year": 2016
                }
            }
        }]
```
I'm working on node 6 with the latest version of chrono.

Another quick question: Is there a convenience method to create a date from all known values of different result subsets? e.g. combine the result for Monday with all knownValues of "noon"?

**Comment by penne12** [comment]
Morning/night/afternoon, etc is ambiguous and outside of the scope of the library to decide, see #126. 

To answer your second question: kind of. Basically, before dates are created (one of the last steps in the library), Chrono sets all of the implied and known values. You could use a custom refiner to set the implied values based on other dates.

In your specific example, Chrono allows for start and end times for dates. Although the 'between' style of writing time ranges you mentioned above is not implemented yet, you could modify [this parser][tep] to add the syntax you mentioned.

[tep]: https://github.com/wanasit/chrono/blob/master/src/parsers/EN/ENTimeExpressionParser.js
