### ISSUE TITLE
The question about the file need to be grab

### ISSUE THREAD

**Issue by kennynaoh** [wanasit/chrono#138]
Hello @wanasit ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question about file want to ask on [npm](https://www.npmjs.com/package/chrono-node).
I think the main file need to grab are `chrono.js` and `chrono.min.js`, right?
But I found that a `sourceMappingURL` in the end of  `chrono.min.js` is `bundle.map`.
Do we also need the `bundle.map`?
If yes, could you offer this file?
Thanks!

And how about `chrono.map.json` and `chrono.min.json`?
I think they are map file for some minified file or js file.
Do we also need these two file?
If yes, could you help me change the file name, maybe like this, `file.map`.
Because `.json` may be confused to us.

Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8222

**Comment by wanasit** [comment]
Hi. Sorry for my slow response.
`chrono.map.json` and `chrono.min.json` are files that automatically created when we combine and minify the source files. You probably don't need those two files if you don't need to debug the minified code.

**Comment by wanasit** [comment]
If you are hosting the library just for you app or website `chrono.js` or `chrono.min.js` (built code) is probably enough.

**Comment by kennynaoh** [comment]
Thanks @wanasit
