### ISSUE TITLE
Add support for ordinal numbers?

### ISSUE THREAD

**Issue by mvolz** [wanasit/chrono#140]
So, I came to this library because Date.parse() does this totally crazy thing where it supports ordinal numbers, but not ordinal indicators, like so:

```
> new Date('May eighth, 2010').toString();
'Sat May 01 2010 00:00:00 GMT+0100 (BST)'
> new Date('May 8th, 2010').toString();
'Invalid Date'
```

So I was pleased this library supports ordinal indicators, which are way more common than ordinal numbers. But now I notice that ordinal numbers are not supported by chrono! (which are supported by Date.parse():

```
> chrono.parseDate('May eighth, 2010')
null
> chrono.parseDate('May 8th, 2010').toString();
'Sat May 08 2010 12:00:00 GMT+0100 (BST)'
```

I know you can add your own parsers, but is native support for ordinal numbers within scope? Thanks!

**Comment by penne12** [comment]
Yes, it is within scope, although technically a feature request, not a bug. If you submit a PR, I'd love to take a look.

**Comment by wanasit** [comment]
Added in 8e33a65.

**Comment by ToFeWe** [comment]
Is there any plan to support this also for other languages like German?
