### ISSUE TITLE
Null results for some ambiguous dates that work with Date.parse()

### ISSUE THREAD

**Issue by mvolz** [wanasit/chrono#141]
Examples:

```
> chrono.parse('2010');
[]
> chrono.parse('Fall 2010');
[]
> chrono.parse('May eighth, 2010');
[]
> chrono.parse('May foo, 2010');
[]

> new Date('2010').toString()
'Fri Jan 01 2010 00:00:00 GMT+0000 (GMT)'
> new Date('Fall 2010').toString()
'Fri Jan 01 2010 00:00:00 GMT+0000 (GMT)'
> new Date('May foo, 2010').toString()
'Sat May 01 2010 00:00:00 GMT+0100 (BST)'
> new Date('May eighth, 2010').toString()
'Sat May 01 2010 00:00:00 GMT+0100 (BST)'
```

**Comment by mvolz** [comment]
(Includes issue #140)

**Comment by penne12** [comment]
'May foo, 2010' looks like 2 different dates to Crono, and adding support for this would break some things come up in natural language:

Example 1:
> I like the month May, and 2010 is my favorite year.

Example 2:
> Could you meet me on Saturday, the 5th of January or sometime else, maybe in 2011?

Chrono is made for natural language parsing, so it is made to handle sentences that may contain multiple or no dates in them.  

On the same point, trying to parse years without other information may result in a #143 style issue. And parsing seasons is a bit difficult. For example:

**When does Fall start each year?
Answer: It depends. And it's a bit outside the scope of this library, it would be an awesome custom parser. Plus, it would make an amazing npm module (give it a year and get the start of the seasons). If you make the npm module and it takes a minimal amount of time to do each calculation and page load, I'd really love to take a look and see if it makes sense. 

 **Have I fallen 7 times, or is it Fall in the year 7AD?**
Again, that's a hard distinction and would result in hilarious results if misinterpreted either way. And sadly, making jokes is outside the scope of this library (you could always use [this one][joke npm], though ;)).

[joke npm]: https://www.npmjs.com/package/one-liner-joke
