### ISSUE TITLE
Bug chrono is parsing phone numbers

### ISSUE THREAD

**Issue by Schultzer** [wanasit/chrono#143]
Chrono is parsing European style phone numbers as valid dates when it should return null
I resolved this is PR #142 

@wanasit 👀

![chrone_bug](https://cloud.githubusercontent.com/assets/10013742/19229923/0b3d0cfe-8e86-11e6-923e-1c6dbf7c5488.jpeg)

**Comment by penne12** [comment]
In PR #142.
