### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by aleix13** [wanasit/chrono#154]
Hey, first of all, I have to say that I'm amazed about your work.

I'm developing an application which uses speech recognition and it could be a great idea using this work in my web app.

My application is in spanish but I don't know how to set properly in spanish.

Thank you

**Comment by penne12** [comment]
Chrono will automatically recognize dates in English, Spanish, French, Japanese and a form of Chinese. If you use the default configuration, there's nothing you have to do. Just use it!
