### ISSUE TITLE
How to extract non-date text

### ISSUE THREAD

**Issue by surrealroad** [wanasit/chrono#157]
This looks perfect for what I need, however given:
`var results = chrono.parse('I have an appointment tomorrow from 10 to 11 AM')`
I'm uncertain as to what I'd need to do to extract the "I have an appointment" part of the text (or indeed if the text was `var results = chrono.parse('From 10 to 11 AM tomorrow I have an appointment')`)

**Comment by arnoldstoba** [comment]
Its pretty easy to remove the interpreted string from the given input. 
I am not sure about how and when exactly chrono removes filler words (e.g. "tomorrow from..."), but in your example this works perfectly fine.

```javascript
var input = 'I have an appointment tomorrow from 10 to 11 AM';
var results = chrono.parse(input);
console.log(input.replace(results[0].text,'')); // I have an appointment
```

**Comment by penne12** [comment]
@arnoldstoba's solution should work.
