### ISSUE TITLE
Basic Dates are not working.

### ISSUE THREAD

**Issue by karungasra** [wanasit/chrono#159]
var chrono = require('chrono-node');

var parsed = chrono.parseDate('from last 2 months');
// Nothing found

var parsed = chrono.parseDate('on 13 12 2016');
// Mon Dec 19 2016 13:00:00 GMT+0530

**Comment by karungasra** [comment]
"Last Monday" and "Next Monday" is working but
"Previous Monday", "Past Monday" and "Coming Monday" are not working.

**Comment by penne12** [comment]
@karungasra Thanks for the feedback. Could you please separate these into separate issues? It helps us keep track of everything better.

**Comment by penne12** [comment]
@karungasra thank you!
