### ISSUE TITLE
'1975 Nov-Dec' interpreted as Dec 1, 2016

### ISSUE THREAD

**Issue by mvolz** [wanasit/chrono#165]
input : '1975 Nov-Dec'
output: 
`
ParsedComponents {
  knownValues: { month: 12 },
  impliedValues: 
   { day: 1,
     year: 2016,
     hour: 12,
     minute: 0,
     second: 0,
     millisecond: 0 } }
`

Not sure anything could be done about this, it is sort of ambiguous, but occasionally the year does come first.

**Comment by Schultzer** [comment]
@mvolz Will a costum parser not solve this issue?

**Comment by mvolz** [comment]
Haven't used one before, I'll give it a go.

**Comment by mvolz** [comment]
Did the trick! Here are the two parsers I added, for posterity :).
`
/* Custom chrono parsers */
var customChrono = new chrono.Chrono();

// Targets partial iso dates, i.e. 1975-10 or 1975-1
var partialISO = new chrono.Parser();
partialISO.pattern = function () { return /([0-9]{4})-([0-9]{1,2})$/g; };
partialISO.extract = function(text, ref, match, opt) {
    return new chrono.ParsedResult({
        ref: ref,
        text: match[0],
        index: match.index,
        start: {
            day: 1,
            month: match[2],
            year: match[1]
        }
    });
};
customChrono.parsers.push(partialISO);

//Target year first with range, i.e. 1975 Dec-Nov
var journalFormat = new chrono.Parser();
journalFormat.pattern = function () { return /(\d{4})\ ([A-Za-z]{3})-[A-Za-z]{3}$/ig; };
journalFormat.extract = function(text, ref, match, opt) {
    // Get month number - a bit hacky
    var month = new Date(Date.parse(match[2] + ' 1, 2010')) ? new Date(Date.parse(match[2] + ' 1, 2010')).getMonth() : 1;
    return new chrono.ParsedResult({
        ref: ref,
        text: match[0],
        index: match.index,
        start: {
            day: 1,
            month: month,
            year: match[1]
        }
    });
};
customChrono.parsers.push(journalFormat);
`
