### ISSUE TITLE
security vulnerabilities in dependencies

### ISSUE THREAD

**Issue by andyjdavis** [wanasit/chrono#176]
Retire (dependency vulnerability checker https://www.npmjs.com/package/retire) reports two vulnerabilities in Chrono's own dependencies.

(path)\node_modules\chrono-node\chrono.js
 ↳ moment.js 2.10.3 has known vulnerabilities: severity: low; summary: reDOS - regular expression denial of service; https://github.com/moment/moment/issues/2936
(path)\node_modules\chrono-node\test\qunit\jquery-1.7.1.min.js
 ↳ jquery 1.7.1.min has known vulnerabilities: severity: medium; bug: 11290, summary: Selector interpreted as HTML; http://bugs.jquery.com/ticket/11290 http://research.insecurelabs.org/jquery/test/ severity: medium; issue: 2432, summary: 3rd party CORS request may execute; https://github.com/jquery/jquery/issues/2432 http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

Would simply bumping up the required version of moment resolve the first one?

Why is there an old jquery file included with chrono-node?

**Comment by penne12** [comment]
We're not actually using `moment.duration()`, and jQuery isn't used outside of testing.

We can push an update to resolve the warning, but these security vulnerabilities don't apply to Chrono directly.

**Comment by andyjdavis** [comment]
I opened this issue approximately years ago. I have attempted to reproduce any dependency related security warnings against current master and I can't. Closing :)
