### ISSUE TITLE
Allow implied past or future

### ISSUE THREAD

**Issue by hazeledmands** [wanasit/chrono#19]
Depending on the context, if today is 2013-12-02,  "Thursday" might mean 2013-11-28 (last Thursday) or it might mean 2013-12-05 (next Thursday). It'd be cool if you could tell chrono to prefer past dates instead of future ones, or vice versa.

(As an example, I am using chrono to parse a command line option for downloading old files created before a certain date. So all of the dates that someone gives me will be in the past, never the future.)

Also, see #5.

PS: Thank you for this library, it is awesome!

**Comment by HaNdTriX** [comment]
The code above doesn't work anymore since the api has changed.
Just in case somebody has the same issue, here my refiner that should work with the latest version (1.0.x).

    var PreferPastLastWeek = new chrono.Refiner();
    PreferPastLastWeek.refine = function(text, results) {
      results.forEach(function(result) {
        if (result.start.isCertain('weekday') && !result.start.isCertain('day')) {
          result.start.imply('day', result.start.impliedValues.day + 7)
        }
      })
      return results;
    };

    chrono.casual.refiners.push(PreferPastLastWeek);
    chrono.strict.refiners.push(PreferPastLastWeek);

Anyway thanks @wanasit for this awesome lib!
