### ISSUE TITLE
Unable to identify 4 digit years. like 2017

### ISSUE THREAD

**Issue by priyankinfinnov** [wanasit/chrono#192]
I have tried 2017 and 2014 - 2017. It does not catch it.

**Comment by mvolz** [comment]
Have you tried a custom parser? 

We have a custom parser for years. It works for our purposes because we're picking dates out of date fields.

The complication is that doing regex is greedy, so if it's in a sentence then you might accidentally leave parts of the date off any only import the year.

**Comment by wanasit** [comment]
Agree with @mvolz. Please use a custom parser. 
We should not just assume 4-digits on every type of text to be a year.

**Comment by pmav** [comment]
I'm using a custom parser to identify specific years using expressions like `/2016/` but isn't working (other example: `/previous year/i` is working fine).

Is this a know bug? If is not I'm glad to help debugging and implementing a fix.
