### ISSUE TITLE
Common date Formats aren't working.

### ISSUE THREAD

**Issue by karungasra** [wanasit/chrono#199]
Working formats:-
08 may 17
08 june 2017
on sunday 20 Aug 2017
May 08 2017

Not Working formats:-
08-may-2017
08/may/17
on sunday 20/Aug/2017
May-08-2017
May/08/17

I Change in ENMonthNameLittleEndianParser and ENMonthNameMiddleEndianParser Pattern to support it.

**Comment by karungasra** [comment]
Working pattern for me of ENMonthNameLittleEndianParser parser for support above all queries.
`var PATTERN = new RegExp('(\\W|^)' +
        '(?:on\\s*?)?' +
        '(?:(Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sun|Mon|Tue|Wed|Thu|Fri|Sat)\\s*,?\\s*)?' +
        '(([0-9]{1,2})(?:st|nd|rd|th)?|' + util.ORDINAL_WORDS_PATTERN + ')' +
        '(?:\\s?\/?-*' +
            '(?:to|\\-|\\–|until|through|till|\\s)\\s*' +
            '(([0-9]{1,2})(?:st|nd|rd|th)?|' + util.ORDINAL_WORDS_PATTERN + ')' +
        ')?\\s?\/?-*(?:of)?\\s*' +
        '(Jan(?:uary|\\.)?|Feb(?:ruary|\\.)?|Mar(?:ch|\\.)?|Apr(?:il|\\.)?|May|Jun(?:e|\\.)?|Jul(?:y|\\.)?|Aug(?:ust|\\.)?|Sep(?:tember|\\.)?|Oct(?:ober|\\.)?|Nov(?:ember|\\.)?|Dec(?:ember|\\.)?)' +
        '(?:' +
            ',?\\s?\/?-*([0-9]{1,4}(?![^\\s]\\d))' +
            '(\\s*(?:BE|AD|BC))?' +
        ')?' +
        '(?=\\W|$)', 'i'
    );`

**Comment by karungasra** [comment]
Working pattern for me of ENMonthNameMiddleEndianParser parser for support above all queries.

`var PATTERN = new RegExp('(\\W|^)' +
    '(?:' +
        '(?:on\\s*?)?' +
        '(Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sun\\.?|Mon\\.?|Tue\\.?|Wed\\.?|Thu\\.?|Fri\\.?|Sat\\.?)' +
    '\\s*,?\\s*)?' +
    '(Jan\\.?|January|Feb\\.?|February|Mar\\.?|March|Apr\\.?|April|May\\.?|Jun\\.?|June|Jul\\.?|July|Aug\\.?|August|Sep\\.?|Sept\\.?|September|Oct\\.?|October|Nov\\.?|November|Dec\\.?|December)' +
    '\\s?\/?-*' +
    '(([0-9]{1,2})(?:st|nd|rd|th)?|' + util.ORDINAL_WORDS_PATTERN +')\\s?\/?-*' +
    '(?:' +
        '(?:to|\\-)\\s*' +
        '(([0-9]{1,2})(?:st|nd|rd|th)?| ' + util.ORDINAL_WORDS_PATTERN + ')\\s?\/?-*' +
    ')?' +
    '(?:' +
        '\\s?\/?-*,?\\s?\/?-*(?:([0-9]{4})\\s*(BE|AD|BC)?|([0-9]{1,4})\\s*(AD|BC))\\s?\/?-*' +
    ')?' +
    '(?=\\W|$)(?!\\:\\d)', 'i');`

**Comment by acrodrig** [comment]
Has this been incorporated into the library already?

**Comment by jonton11** [comment]
+1 I would also like to know

**Comment by wanasit** [comment]
Added in 90ffaf9.

@karungasra would be nice if you could submit MR with tests next time.
