### ISSUE TITLE
Some date formats are not parsed correctly

### ISSUE THREAD

**Issue by chiptus** [wanasit/chrono#202]
First of all, thanks for a great package.

The following formats are not parsed correctly:
* 3 min 49 sec ago - returns null
* 1 day 21 hours ago - parses only '21 hours ago', missing the 1 day.
* same for 5 hours 29 min ago - missing the 5 hours.

Thanks again

**Comment by wanasit** [comment]
Supported in 1f93cb0

**Comment by chiptus** [comment]
thanks!
