### ISSUE TITLE
Language Confusion

### ISSUE THREAD

**Issue by HelloEdit** [wanasit/chrono#203]
Hello,

First, I love your work, this librairie is just awesome !
So, secondly, when I parse "Quel est mon emploi du temps demain ?"
(traduction: What is my schedule tomorrow ?)
chrono found demain as tomorrow, but found "mon" like monday.

So, is it possible to tell the module to use just FR ?
 
Thank you,

**Comment by TheRealTau** [comment]
I think there is not a parameter or config to do that yet but you can try something by your own, inside chrono.js, parser.js and options.js  are the specific lines than config the parsers and refiners for every language, you can comment the ones you dont really need and then just make chrono from scratch with this changes. Another idea is change the options.js so it iterate over a specific language parsers.
Maybe the best option is to create your own option settings, inside options.js there is a casualOption which is the one than chrono imports by default, you could create and use an specific options setting which use only FR parsers. A little tricky but i hope it help you.

**Comment by HelloEdit** [comment]
You're awesome, thank !
