### ISSUE TITLE
x time from now not parsed correctly

### ISSUE THREAD

**Issue by intoxicatedpenguin** [wanasit/chrono#204]
10 minutes from now is only seen as 'now' it seems, even when passed Date.now() as a reference. This also applies to hours, days, etc. Thank you.

**Comment by alexgorbatchev** [comment]
`in 10 minutes` seems to work as expected... but yeah, `10 minutes from now` should probably also work.

**Comment by wanasit** [comment]
Fixed in d6f06d65fd592c72cccccf3eefa308f295e9e97f. Thanks @jonshaffer.
