### ISSUE TITLE
Not an issue - a request for a little assistance

### ISSUE THREAD

**Issue by inkeytech** [wanasit/chrono#211]
Hello,

I really like node-chrono. I can see a lot of work went into it. Thank you for sharing.

Please can you point me in the right direction.

I would like to change the behaviour to always 'assume' dates and times are in the future, if not specifically noted.

So, if 'Monday' is entered, regardless of the current day, the next Monday in the **future** is 'assumed'.

If 5:30 is entered, and 5:30 AM has already passed, then 5:30 in the evening is assumed.

Do I create my own parser/s, or my own refiner/s, or do I change existing ones.

Any advice would be greatly appreciated.

Regards,

Ian Watson

**Comment by wanasit** [comment]
hi. You can use `forwardDateOnly` option. There are discussions about this in the past.
* https://github.com/wanasit/chrono/issues/173
* https://github.com/wanasit/chrono/issues/19

You can also write [a custom refiner](https://github.com/wanasit/chrono#refiner) (see. how [ForwardDateRefiner.js](https://github.com/wanasit/chrono/blob/master/src/refiners/ForwardDateRefiner.js) works) that e.g. throws an exception if detecting some dates in the past.
