### ISSUE TITLE
Parsing "today" returns today's date at 12:00 pm (instead of AM)

### ISSUE THREAD

**Issue by ppissanetzky** [wanasit/chrono#217]
> chrono.parseDate("today");
2017-08-30T19:00:00.000Z

> chrono.parseDate("today").toLocaleString();
'8/30/2017, 12:00:00 PM'

**Comment by wanasit** [comment]
This is not a bug. Chrono implies the time is the mid-day (12 PM) when it's not mentioned.
- #135
