### ISSUE TITLE
UK date format support

### ISSUE THREAD

**Issue by Kyle-MacKinnon** [wanasit/chrono#221]
People who use UK dates like to use (day/month/year) not (month/day/year) like Americans.

It's just crucial if you're building code in one of the many places that use this format, like me in New Zealand.

Realistically I would like to set it to parse using UK format by default. Currently I have to use a very bulky work around that involves swapping day and month myself under certain conditions.

**Comment by brunoogonzalez** [comment]
It happens the same in other countries in Latin America. Thanks!

**Comment by capaj** [comment]
same here in Czech republic.

**Comment by wanasit** [comment]
Thank you for the feedback. 

Chrono now has an easy option to select the locale. Please see the updated README:
https://github.com/wanasit/chrono/blob/master/README.md#customize-chrono
