### ISSUE TITLE
Milliseconds not parsed (in this format)

### ISSUE THREAD

**Issue by AlbinoDrought** [wanasit/chrono#225]
Hey, great library! Currently dealing with date strings in unknown formats, and came across these that are parsed to be the same:

```js
var chrono = require('chrono-node')
console.log(chrono.parseDate('09/25/2017 10:31:50.5223 PM').getTime())
console.log(chrono.parseDate('09/25/2017 10:31:50.6142 PM').getTime())
```

Output:
```js
1506360710000
1506360710000
```

I think the expected output would be:
```js
1506360715223
1506360716142
```

There was this pull request that seemed relevant, but it was merged a while ago: https://github.com/wanasit/chrono/pull/44

I'll probably end up throwing together a parser for this, unless one already exists.

(Actually, these seem to be portion-of-seconds instead of milliseconds - 6000ms doesn't make sense)

**Comment by wanasit** [comment]
Add millisecond parsing support in 03aa029. 

The number after dot is "a decimal fraction of a second" in ISO8601. Because we support unto millisecond, I round those number of after the third digits.
