### ISSUE TITLE
parseDate - moment.locale is not a function when bundling with webpack

### ISSUE THREAD

**Issue by tomoakley** [wanasit/chrono#229]
Having an issue while using `parseDate` - it reports an error from moment, `TypeError: moment.locale is not a function. (In 'moment.locale()', 'moment.locale' is undefined)`. I believe the issue is the same as <a href="https://github.com/moment/moment/issues/4216">this</a> - I am using webpack to build my bundle - and can be fixed my updating moment.js to 2.19.1.

**Comment by wanasit** [comment]
Thanks for letting me know. I actually able to solve this by rolling back and lock down the moment.js at 2.10.3. I'll keep using the 2.10.3 because I haven't tested the recent version of moment.js and we don't need those features anyway.

bcc64a34f60a94fb244ba4b7cd9a992348079363
