### ISSUE TITLE
forwardDate option does not force year forward

### ISSUE THREAD

**Issue by rrcobb** [wanasit/chrono#240]
chrono-node@1.3.5

```
> chrono.parseDate('January 8 at 12pm', new Date(), { forwardDate: true })
=> 2018-01-08T20:00:00.000Z          // as expected

> chrono.parseDate('1/8 at 12pm', new Date(), { forwardDate: true })
=> 2017-01-08T20:00:00.000Z          // !?!?!?!?!
```

It looks like the forward date refiner depends on the year only being implied and not certain before it does its refinement. For some reason, the year coming through as certain. 

I assume the issue is with `chrono/src/parsers/EN/ENSlashDateFormatParser.js`, since that's the parser that applies and does something with year:

```
> chrono.parse('1/8 at 12pm', new Date(), { forwardDate: true })
=> [ParsedResult {
  ref: 2017-12-07T22:50:44.614Z,
  index: 0,
  text: '1/8 at 12pm',
  tags:
   { ENSlashDateFormatParser: true,
     ENTimeExpressionParser: true,
     ENMergeDateAndTimeRefiner: true },
  start:
   ParsedComponents {
     knownValues:
      { day: 8,
        month: 1,
        year: 2017,
        hour: 12,
        minute: 0,
        second: 0,
        meridiem: 1 },
     impliedValues: { millisecond: 0 } } }]
```

I assume that there is some match on year where there shouldn't be, or it's  `assign` ing instead of `imply`ing year. 

Let me know if you need any more information to reproduce this, or if there is a clear culprit for a fix.

**Comment by nbikar** [comment]
I would like to add another example to this:

`chronoNode.parse('30 may 2 jun',{forwardDate: true})`

```
0: ParsedResult
index: 0
ref: Object {forwardDate: true}
start: ParsedComponents
impliedValues: Object {hour: 12, millisecond: 0, minute: 0, second: 0}
knownValues: Object {day: 30, month: 5, year: **2002**}
ParsedComponents Prototype
tags: Object {ESMonthNameLittleEndianParser: true}
text: "30 may 2"
ParsedResult Prototype
```

**Comment by oltreseba** [comment]
This is currently still happening. 
If today, 2nd of February 2020, I try to parse:
`February`, it's interpreted as `yesterday` (even with { forwardDate: true })

**Comment by wanasit** [comment]
Sorry for my super slow reply. The problem has already been fixed for some time.
(see. 699c871)

**Comment by oltreseba** [comment]
I think the issue is still there:
Today is 28 of September and if it try to resolve "September" with `{forwardDate: true}` I still get September 2021 and not 2022:

<img width="990" alt="Screenshot 2021-09-28 at 10 02 00 AM" src="https://user-images.githubusercontent.com/5563210/135047902-70479b08-c758-45a6-b4f3-e301fa5f15fe.png">

```JS
const chrono= require('chrono-node')
console.table(chrono.parse('September', { forwardDate: true })[0].start)
```
