### ISSUE TITLE
Extracting wrong date when an invalid date is entered

### ISSUE THREAD

**Issue by spddheeraj** [wanasit/chrono#245]
Extracting wrong date when an invalid date is entered. In this case it is expected to not extract any date.
Eg. "I have an appointment on 13/31/2018"

<img width="367" alt="screen shot 2018-02-22 at 4 36 41 pm" src="https://user-images.githubusercontent.com/5276201/36535115-9e9c5ef8-17ee-11e8-8f10-bf74541799af.png">

**Comment by keithcrooksbbc** [comment]
I have seen the same thing. In my unit tests I purposefully entered an incorrect data of '2019-02-30' and expected to not get a result. Instead it defaulted to the current datetime of 2019-10-10T10:32:19.145Z.

Output:

```
[
    ParsedResult {
        ref: 2019-10-10T10:32:19.145Z,
        index: 1,
        text: '2019-02-30',
        tags: [Object],
        start: [ParsedComponents]
    }
]
```

Is this the expected behaviour?

**Comment by paddymul** [comment]
Is it possible to make the parser more strict for cases like this?

**Comment by wanasit** [comment]
I cannot reproduce this issue in the test.
38d0c0abf7f7a570a4010b8f3a5f09345568872a

I think it has already been fixed recent changes.
