### ISSUE TITLE
Cannot parse year only

### ISSUE THREAD

**Issue by czechdave** [wanasit/chrono#246]
`chrono.parseDate('1987')` returns `null`, would expect to get `Thu Jan 01 1987 12:00:00`

**Comment by mvolz** [comment]
Duplicate of #192

This issue was previously declined. This is because chrono is designed for natural language processing, and picking out just the year is often too greedy. However, you can use a custom parser if you would like to do this with chrono. 

Here's an example of a custom parser: 

```
const chrono = require('chrono-node');
/* Custom chrono parsers */
const customChrono = new chrono.Chrono();

// Targets partial iso dates, i.e. 1975-10 or 1975-1
const partialISO = new chrono.Parser();
partialISO.pattern = () =>  /([0-9]{4})-([0-9]{1,2})$/g;
partialISO.extract = (text, ref, match, opt) => {
    return new chrono.ParsedResult({
        ref,
        text: match[0],
        index: match.index,
        start: {
            month: match[2],
            year: match[1]
        }
    });
};
customChrono.parsers.push(partialISO);
```

**Comment by czechdave** [comment]
That makes sense, thanks for the snippet!
