### ISSUE TITLE
IST is Irish Standard Time and not Indian Standard Time

### ISSUE THREAD

**Issue by ParthKolekar** [wanasit/chrono#254]
This is a weird request, but I want IST to be Indian Standard Time (+330), rather than Irish Standard Time (+60). 

One reason I want this is because +60 already has `A, BST, CET,MEZ,WAT,WEST,WESZ` as a representation. 

Indian Standard Time, does not have anything else to represent +330. 

The correct way to solve this issue, is to never use 3 letter code -> timezone because there are too many such ambiguous conversions.

**Comment by wanasit** [comment]
Changed the default value. I also added option to override the timezone abbreviation. You can now do:
```
chrono.parse('Friday at 2 pm IST', refDate, {'IST': 330})[0].start.get('timezoneOffset');
// 330 (IST – India Standard Time +0530)
```
