### ISSUE TITLE
Choosing a locale for parsing

### ISSUE THREAD

**Issue by Clemaul** [wanasit/chrono#258]
chrono.parseDate("14/12/1993") return a date like 14 december 1993
but chrono.parseDate("04/12/1993") return a date like 12 april 1993

in first case, date is parsed as "DD/MM/YYYY"
in second case, date is parsed as "MM/DD/YYYY"

is it a problem or is it possible to alway parse date as "DD/MM/YYYY" (french format) ?

**Comment by wanasit** [comment]
Try `chrono.en.parseDate()` vs `chrono.en_GB.parseDate()`.
https://github.com/wanasit/chrono/commit/5243b82cf8b84045e3389a0bf5e6464293434a3d
