### ISSUE TITLE
Custom Parser matching with DMY date format

### ISSUE THREAD

**Issue by ProxyPy** [wanasit/chrono#272]
I am trying to make a greedy date parser that will mostly be used on classic European date format (DMY).\
So, when the parser find this date : *11/12/2018*, I want it to understand "11th December 2018" instead of "November, 12th 2018".\
However, I cannot find a way to achieve that in the documentation. I assume that it has something to do with setting a `new chrono.Chrono()` properly but since I am pretty new to JS, I have trouble exploring the possibilities. **Is there a way to do it ?** The absolute best solution would be to have the possibility to set the date format like the vanilla chrono (`chrono.en_GB.parseDate("01/01/2011");` / `chrono.de.parseDate("01/01/2011");`) but having a custom parser that can only handle DMY is still great.\
The date format I am refering to is explained here : [https://en.wikipedia.org/wiki/Date_format_by_country](https://en.wikipedia.org/wiki/Date_format_by_country).\
Thank you for reading :)

**Comment by wanasit** [comment]
Sorry for my slow reply. I hope you have found a way to do that. 

If not, please check the `options.js` to understand how the country configuration is created and re-adjust you parsers accordingly.

**Comment by jessep** [comment]
Hi, @wanasit  I don't see options.js or options.ts anymore. Is there still a way to do this?

**Comment by wanasit** [comment]
yes. It's designed into [Configuration](https://github.com/wanasit/chrono/blob/master/src/chrono.ts#L10). You can check how to setup a new configuration from example in locales (e.g. `src/locales/en/index.ts`)
