### ISSUE TITLE
Setting IST value had no effect on the result

### ISSUE THREAD

**Issue by prakis** [wanasit/chrono#273]
If I run the following code on a server(with UTC timezone) it always gives same result for any IST value

Note the IST value for the following two commands is different (330, 60)
> result = chrono.parse("4pm IST", new Date(), {forwardDate:true,'IST':330 })[0].start.date();
2018-09-10T15:00:00.000Z
> result = chrono.parse("4pm IST", new Date(), {forwardDate:true,'IST':60 })[0].start.date();
2018-09-10T15:00:00.000Z

I wonder why setting IST had no effect on the result ?

More details: I am trying to set the timezone  for chrono to run with instead of using the server timezone.

**Comment by wanasit** [comment]
Sorry. I made a mistake in the document. the timezone should be passed as nested `timezones` in the option object.
```
chrono.parse("4pm IST", new Date(), {forwardDate:true, timezones: {'IST':330} })[0].start.date();
```
