### ISSUE TITLE
Error in example in README?

### ISSUE THREAD

**Issue by NicoWeio** [wanasit/chrono#280]
In the README:
```
// 'casual' mode (default) 
chrono.parseDate('Today');              // Thu Jun 30 2016 12:00:00 ...
chrono.casual.parseDate('Friday');      // Fri Jul 01 2016 12:00:00 ...
chrono.casual.parseDate('Jul 01 2016'); // Fri Jul 01 2016 12:00:00 ...
chrono.casual.parseDate('Friday');      // Fri Jul 01 2016 12:00:00 ...
```

The line `chrono.casual.parseDate('Friday');      // Fri Jul 01 2016 12:00:00 ...` appears twice and the first line of code does not have a `.casual` - something seems to be wrong there.

**Comment by wanasit** [comment]
Thank you for pointing out. Fixed in 47ea9ab5a1c88c0f902a92603ebf34adb01730e8
