### ISSUE TITLE
Is it in develomment?

### ISSUE THREAD

**Issue by gagan-bansal** [wanasit/chrono#281]
Such a wonderful lib, I am using it in many projects.

But I see there is no further development or maintenance 
What are the future plans @wanasit.

Gagan

**Comment by wanasit** [comment]
Thank you for pinging me. And sorry for being very unresponsive. 

For me, building and maintaining this library is a personal challenge I do from time to time to practice programming. So, I don't really have any big future plans in mind.

**Comment by gagan-bansal** [comment]
Thank you for quick response. 
This is the only library comparable to duckling. 
Great work!
