### ISSUE TITLE
Moment.js bundle size too large

### ISSUE THREAD

**Issue by xxyuk** [wanasit/chrono#285]
Hello,
Thank you for the great library!

Day.Js is a nice alternative to me, seems we only have to replace `moment` to `dayjs` without any other code change to reduce bundle size from 60kb (moment) to  2kb (dayjs)

-----

ref: 

⏰ Day.js 2KB immutable date library alternative to Moment.js with the same modern API

https://github.com/iamkun/dayjs

**Comment by wanasit** [comment]
Thank you very much for letting me know. And sorry for my slow response.
Day.js looks like a better choice for Chrono. Will find some time to replace that.

**Comment by andypearson** [comment]
There is also [date-fns](https://date-fns.org) which could result in an even smaller bundle size as you only need to require the bits you actually use.

**Comment by scamden** [comment]
@wanasit I was just coming here to recommend day.js as well. any chance we could get a quick release on that? the contract is nearly identical and moment is HUGE!

**Comment by tamirvs** [comment]
Yes it's a shame:

![img](https://user-images.githubusercontent.com/1403080/72202143-e44f5600-3464-11ea-97fe-cb6f568c0c49.png)

**Comment by wanasit** [comment]
Really sorry for my laziness and delay... 
This has been worked on. Please update to chrono 1.4+
