### ISSUE TITLE
Is it possible to change locale for custom Chrono?

### ISSUE THREAD

**Issue by Booligoosh** [wanasit/chrono#299]
Normally, if I want to use the `en_GB` locale, I can just write this:
```
chrono.en_GB.parseDate('21/08/2019')
```
However, I have a custom chrono (so I can add parsers), set up like this:
```
const customChrono = new chrono.Chrono()
customChrono.parsers.push(myParser)
```
I want to be able to parse dates using `customChrono` with the `en_GB` locale. I've tried this:
```
customChrono.en_GB.parseDate('21/08/2019') // Doesn't work
```
And it doesn't work.

Is it possible to parse dates from a custom Chrono with `en_GB`?

**Comment by wanasit** [comment]
Sorry for my slow replay.

First, if you look into how parsers and refiners option is composed in `src/options.js` and `src/chrono.js`, you should be able to find a way to create an option of parsers that works well on your case.

This is NOT recommended, but if you don't care about the global namespace, you can just change the `chrono.en_GB` directly. 
```
chrono.en_GB.parsers.push(myParser)
```
