### ISSUE TITLE
"in one day" doesn't behave the same as "in 24 hours"

### ISSUE THREAD

**Issue by Mstrodl** [wanasit/chrono#301]
Is there any way I can make 'tomorrow' and 'in one day' behave the same as 'in 24 hours'? Right now it appears to just use 12:00 the next day instead of exactly 24 hours from the message.

Code sample:
```js
const chrono = require("chrono-node");
const date = new Date();
// these should be equal, but they're not
chrono.en.parse("in 24 hours test", date)[0].start.date().getTime() == chrono.en.parse("in 1 day test", date)[0].start.date().getTime()
```

**Comment by thomasin** [comment]
Would love to know if this is intentional behaviour, happy to work on a solution or another option to make these line up

**Comment by cnicodeme** [comment]
Curious about this too!

This problem also applies on every "date" changes like "in a week".

**Comment by Mstrodl** [comment]
@wanasit Going to mention you so it shows up in your notifications

**Comment by wanasit** [comment]
Sorry for my slow reply. The behavior that you see is that Chrono doesn't imply the time from the refDate when it parses deadlines with day-level granularity. It simply fall back to the default time of that day.

e.g. 

```
const date = new Date(2020, 7-1, 11, 14, 13); // Now, it's [2020-07-11 14:13]
chrono.en.parse("in 24 hours", date) // this is exactly 24hr from now -> [2020-07-12 14:13]
chrono.en.parse("in one day", date) // this is 'sometime' tomorrow -> [2020-07-12 12:00]
``

I'm changing this in 5282892 (v2.x.x). Chrono will imply the time from the current date. Those two parsing results should be the same.
