### ISSUE TITLE
leaked global in ENTimeLaterFormatParser

### ISSUE THREAD

**Issue by clocked0ne** [wanasit/chrono#302]
The variable `index` is picked up by mocha test runner when checking for leaks:
```js
Error: global leak detected: 'index'
```
`node_modules\chrono-node\src\parsers\en\ENTimeLaterFormatParser.js:40:15`

```js
index = match.index + preamble.length;
```

This should be declared using `var` to avoid becoming global:
```js
var index = match.index + preamble.length;
```

**Comment by wanasit** [comment]
Fixed in c21fae0. Thanks for reporting this.
