### ISSUE TITLE
Unable to parse date format 03 Aug 96

### ISSUE THREAD

**Issue by tienzochi** [wanasit/chrono#303]
Expected: 03 Aug 96 should be parsed to 03 Aug 1996
Actual: 03 Aug 96 is parsed to 03 Aug 2019

Two digit year has been working in the past but not sure when it stopped working. Any help/comment is appreciated :D

**Comment by gagan-bansal** [comment]
Its being parsed as 2096. (version 1.3.5). I think logic is fine.
Because its difficult to guess 20 as 2020 or 1920.

**Comment by wanasit** [comment]
This should be fixed in 31d2a61
