### ISSUE TITLE
The exact time in the string gets autocorrected to a time interval

### ISSUE THREAD

**Issue by hshercha** [wanasit/chrono#304]
If there is an exact time and a time interval in the string, the exact time gets converted to a time interval.

"I will see you at 2:30. If not I will see you somewhere between 3:30-4:30pm"
gets converted to
"I will see you at 2:30-4:30pm. If not I will see you somewhere between 3:30-4:30pm"

Verified this via Runkit as well
https://runkit.com/embed/vyiwiprzbc01

<img width="762" alt="Screen Shot 2019-09-13 at 2 24 13 PM" src="https://user-images.githubusercontent.com/10735656/64895788-6b64fc80-d632-11e9-8b78-ca4778e9dcb2.png">

**Comment by wanasit** [comment]
Thanks for letting me know. This should work in `v2.x.x`.
I also patched this in `v1.4.7`.
