### ISSUE TITLE
SlashMonthFormatParser parses date incorrectly

### ISSUE THREAD

**Issue by dulebov-artem-workflowy** [wanasit/chrono#307]
chrono.parse('06/2005')

RESULT
[{"ref":"2019-11-01T15:22:21.334Z","index":0,**"text":"06/200"**,"tags":{"ENSlashMonthFormatParser":true},"start":{"knownValues":{"month":6,"year":2005},"impliedValues":{"day":1,"hour":12,"minute":0,"second":0,"millisecond":0}}}]

Expected result

[{"ref":"2019-11-01T15:22:21.334Z","index":0,**"text":"06/2005"**,"tags":{"ENSlashMonthFormatParser":true},"start":{"knownValues":{"month":6,"year":2005},"impliedValues":{"day":1,"hour":12,"minute":0,"second":0,"millisecond":0}}}]

**Comment by wanasit** [comment]
Thanks for letting me know.
Should be fixed in c8ebfd2bc0f72498dbbbb66f8f235f6f4ac63dce
