### ISSUE TITLE
ES6 module fails on import

### ISSUE THREAD

**Issue by mikemaccana** [wanasit/chrono#311]
In `src\parsers\en\ENISOFormatParser.js:11`

`Uncaught TypeError: Cannot read property 'Parser' of undefined`

`var Parser = require('../parser').Parser;`

**Comment by mikemaccana** [comment]
Note this is using ES6 modules: 

` import { parseDate } from "chrono-node"`

Using rollup. In chrono's `package.json` there is `"main": "./src/chrono",` which implies this works as an ES6 package, but something's broken.

**Comment by wanasit** [comment]
I believe this has been fixed with the new build process in 1.4.4
