### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by wibblymat** [wanasit/chrono#314]
I saw that you bumped the version in `package.json` to 1.4.2, but I don't see that version in npm.

Would love to be able to install the latest version from npm.

Thanks!

**Comment by eran-pinhas** [comment]
@wanasit will it be possible?

**Comment by wanasit** [comment]
Sorry, I simply forgot to do that yesterday.
https://www.npmjs.com/package/chrono-node

**Comment by eran-pinhas** [comment]
Thanks @wanasit :heart:
