### ISSUE TITLE
"7 años" gets parsed as 7am, with strict mode on.

### ISSUE THREAD

**Issue by KevinNovak** [wanasit/chrono#318]
Input: `7 años`
Captured: `7 a`

Strict mode is enabled.

Maybe when matching the hour am/pm pattern, check if if the `a` is either followed by a space ` `, followed by an `m`/`M`, or at the end of a line.

**Comment by benaubin** [comment]
Try using only the `es` locale, we probably won't fix this as it looks like a conflict between locales.
