### ISSUE TITLE
Type Declarations for Typescript Support

### ISSUE THREAD

**Issue by dcgudeman** [wanasit/chrono#322]
Hi there,

Great library but I am currently working in a typescript environment and I was wondering if there are any complimentary libraries or planned development to support typescript.

**Comment by benaubin** [comment]
Hi there, @dcgudeman. That's a great idea. I'd be happy to write a type declaration file.

**Comment by wanasit** [comment]
Hey @benaubin! Thank you for working on this. 

Just FYI. I also want to switch to TypeScript as a long-term plan, but it would be a lot of work. Recently, I worked on refactoring the build. I am also thinking about refactoring class into ES6-style-class, not legacy-prototype.

**Comment by benaubin** [comment]
@wanasit Of course! I'm excited to get back into being involved here - and I'm very excited about the potentials for a TS rewrite.  

If we're going to be considering a rewrite, here are my thoughts:

- In my opinion, there's very little reason we should attempt to parse multiple languages at once by default. Doing so leads to a bunch of corner cases, like #319. Multi-lingual apps already have to track the user's language, so I'm not sure there's really a need for our attempts of auto-detection.
- I think it'd be wise to separate Chrono's core and locales into multiple packages (`@chrono/core`, `@chrono/locale-en`, etc). Hopefully, we can do so in a way that would easily allow the creation of community maintained locales. [lerna](https://github.com/lerna/lerna) seems to have made this much easier.

**Comment by benaubin** [comment]
Closing because a full Typescript rewrite is coming (#323)
