### ISSUE TITLE
Typescript Rewrite

### ISSUE THREAD

**Issue by benaubin** [wanasit/chrono#323]
Continuing the conversation from #322:

> @wanasit 
> Just FYI. I also want to switch to TypeScript as a long-term plan, but it would be a lot of work. Recently, I worked on refactoring the build. I am also thinking about refactoring class into ES6-style-class, not legacy-prototype.

 If we're going to be considering a rewrite, here are my thoughts:

 - In my opinion, there's very little reason we should attempt to parse multiple languages at once by default. Doing so leads to a bunch of corner cases, like #319. Multi-lingual apps already have to track the user's language, so I'm not sure there's really a need for our attempts of auto-detection.
 - Now that it seems like the JS community has settled on NPM, I think it'd be wise to separate Chrono's core and locales into multiple packages (@chrono/core, @chrono/locale-en, etc). Hopefully, we can do so in a way that would easily allow the creation of community maintained locales. lerna seems to have made multi-package development easier.
- We should consider swapping Moment for [Luxon](https://moment.github.io/luxon/)

**Comment by wanasit** [comment]
Hey Ben.

Thanks for your suggestion.

> We should consider swapping Moment for Luxon
I've already replaced Moment with Dayjs (https://github.com/wanasit/chrono/pull/313, https://github.com/wanasit/chrono/issues/285)

I've never heard of Luxon before. I will check it out.

> In my opinion, there's very little reason we should attempt to parse multiple languages at once by default. Doing so leads to a bunch of corner cases, like #319. Multi-lingual apps already have to track the user's language, so I'm not sure there's really a need for our attempts of auto-detection.

Yes, agree. Running all parsers was an incorrect decision. We should separate and contain each locale's rules and setting.

> Now that it seems like the JS community has settled on NPM, I think it'd be wise to separate Chrono's core and locales into multiple packages (@chrono/core, @chrono/locale-en, etc). Hopefully, we can do so in a way that would easily allow the creation of community maintained locales. lerna seems to have made multi-package development easier.

Thanks for your suggestion. I've never heard of `lerna`. 
Let me check it out and think more about this.

However, I'm not sure about breaking Chrono into multiple packages. Having users import both `chrono/core` and `chrono/en` has unclear benefits.

**Comment by benaubin** [comment]
@wanasit Primary benefit of breaking up into multiple packages is that it would make community-supported locales first-class citizens. No need for us to maintain locale code for languages we don't know.

**Comment by wanasit** [comment]
@benaubin Sorry for the delay. The rewrite is pretty big and includes some incompatible change. So, this is going to be a new major version (v2).

Would you have time to see the change in the branch and leave me some comments? I'm thinking about rolling out the v2 next weekend.
https://github.com/wanasit/chrono/tree/typescript

### What's changed in v2

For Users
* Chrono’s default now handles only international English. While in the previous version, it tried to parse with all known languages.

For contributors and advanced users
* The project is rewritten in TypeScript
* New [Parser](#parser) and [Refiner](#refiner) interface 
* New source code structure. All parsers, refiners, and configuration should be under a locale directory (See. `locales/en`)

**Comment by benaubin** [comment]
Sure thing! Could you start a PR so I can do a review?

**Comment by wanasit** [comment]
Here the PR:
https://github.com/wanasit/chrono/pull/328

It's pretty big (as you would expect from a rewrite). I actually think it may be easier if you just checkout the branch.

**Comment by benaubin** [comment]
@wanasit Cool! Got caught up in a huge issue with another project, so it might be a few days. Excited to see the changes 😄

**Comment by wanasit** [comment]
@benaubin I had to continue fixing bugs and rollout more updates, so I just merged the `typescript` branch into this master today. Hope you don't mind.

Please feel free to continue to send me feedback or MR to fix my design later.

**Comment by benaubin** [comment]
No worries. Sorry I haven't gotten a chance to look at it yet. I'll try to get around to it tomorrow morning.
