### ISSUE TITLE
Casual time ignores timezone

### ISSUE THREAD

**Issue by cco3** [wanasit/chrono#325]
> require('chrono-node').parseDate('Jan 1, 2020 6:00 UTC')
    2020-01-01T06:00:00.000Z
    > require('chrono-node').parseDate('Jan 1, 2020 Morning UTC')
    2020-01-01T14:00:00.000Z
    > require('chrono-node').parseDate('Jan 1, 2020 6:00')
    2020-01-01T14:00:00.000Z
    > require('chrono-node').parseDate('Jan 1, 2020 Morning')
    2020-01-01T14:00:00.000Z

I would expect the second command to produce the same result as the first.

**Comment by wanasit** [comment]
Thanks for reporting this. This problem has already been fixed in v2+ (as shown in the test added in 66af6adc6f1452ea2fcec4bc9b0c7984e94a5203)
