### ISSUE TITLE
Ambiguous meridiem with timezone starting with P parses as PM in local timezone

### ISSUE THREAD

**Issue by Lovinity** [wanasit/chrono#329]
Code:
chronoNode.parseDate("9:00 PST");

Expected behavior:
Parses as ambiguous meridiem in Pacific Standard Time

Actual behavior:
Parses as 9:00 PM in the local chronoNode timezone (because the timezone begins with a P).

This bug is not present when using military time (no colon), specifying AM/PM, or using a timezone that does not begin with A or P.

**Comment by wanasit** [comment]
This has already been fixed in `v2.x.x`.

**Comment by Lovinity** [comment]
Thank you. But version 2 was not yet released as stable at the time I posted this, and I didn't find any other issues like this open (so I had no idea). I feel spoken down to by the wording which could have been avoided by saying it has been (rather than already) fixed in the recently released version 2. I appreciate the understanding.

**Comment by wanasit** [comment]
Hello @Lovinity. First, thanks for reporting this. 

It's not my intention to make you feel spoken down. I was just trying to go through several open issues today and didn't pay enough attention to my reply message. (Please also understand that I'm not even an English native speaker). 

I apologize for my earlier reply.
