### ISSUE TITLE
Doubtful Regexp

### ISSUE THREAD

**Issue by apoorv-mishra** [wanasit/chrono#330]
Shouldn't `\s` occurrences  at https://github.com/wanasit/chrono/blob/c3024a60d5f5de5d19430b0ccf7010f4ec860a66/src/parsers/en/ENSlashDateFormatParser.js#L28 be `\\s`? Or is it for some other purpose?

**Comment by wanasit** [comment]
Thanks for reporting this. This has already been fixed if you check the latest file `ENSlashDateFormatParser.ts`
