### ISSUE TITLE
Add Safari and Firefox ESR support

### ISSUE THREAD

**Issue by fdemello** [wanasit/chrono#332]
https://github.com/wanasit/chrono/blob/ea3c8e166ce922655b71b87c4599c629ddda429e/src/locales/en/parsers/ENCasualDateParser.ts#L9

Web apps that leverage this library cannot be used in Safari due to the use of positive lookbehind. Can a workaround be put in place so Safari can be used?

**Comment by ncehreli** [comment]
Fails with latest Firefox ESR release (68.10.0ESR) as well :

let test = /(?<=\W|^)(now|today|tonight|last\s*night|tomorrow|tmr|yesterday)(?=\W|$)/i; 
SyntaxError: invalid regexp group

**Comment by wanasit** [comment]
Thanks for letting me know. I have published `2.0.3` without any lookbehind usage.

**Comment by fdemello** [comment]
@wanasit Thanks for fixing that! There's one more place where positive lookbehind is used: https://github.com/wanasit/chrono/blob/v2.1.0/src/locales/en/parsers/ENTimeUnitAgoFormatParser.ts#L16

```
SyntaxError: Invalid regular expression: invalid group specifier name
./node_modules/chrono-node/dist/locales/en/parsers/ENTimeUnitAgoFormatParser.js
node_modules/chrono-node/dist/locales/en/parsers/ENTimeUnitAgoFormatParser.js:23
  20 |     '(?:within\\s*)?' +
  21 |     '(' + constants_1.TIME_UNITS_PATTERN + ')' +
  22 |     '(?:ago|before|earlier)(?=(?:\\W|$))', 'i');
> 23 | var STRICT_PATTERN = new RegExp('' +
  24 |     '(?<=\\W|^)' +
  25 |     '(?:within\\s*)?' +
  26 |     '(' + constants_1.TIME_UNITS_PATTERN + ')' +
```

**Comment by wanasit** [comment]
Ops. I'm really sorry for my clumsiness.
Are you able to update to `v2.1.1`?

**Comment by fdemello** [comment]
@wanasit I tested v2.1.2 and it's working great. Thanks!
