### ISSUE TITLE
Parser and refiner documentation is outdated for v2

### ISSUE THREAD

**Issue by lostfictions** [wanasit/chrono#335]
In the readme, the examples for both parser and refiner start like this:

```javascript
const custom = chrono.casual.copy();
```

However, if I try this in the REPL using `chrono-node@2.1.3`, `chrono.casual.copy` does not exist:

```
$ node
Welcome to Node.js v14.2.0.
Type ".help" for more information.
> const chrono = require('chrono-node')
undefined
> typeof chrono.casual
'object'
> chrono.casual.copy
undefined
> chrono.casual.copy()
Uncaught TypeError: chrono.casual.copy is not a function
```

**Comment by wanasit** [comment]
Thanks for letting me know. I've just updated the readme file.
Please use `chrono.casual.clone()`, not `copy`.
