### ISSUE TITLE
How do I make "tomorrow" be interpreted as "in 24 hours"?

### ISSUE THREAD

**Issue by lostfictions** [wanasit/chrono#336]
Hi, thank you for this library! It's been very helpful for my project.

Currently I'm using the library in a chatbot that runs on Slack and Discord where users are across multiple time zones and the bot does not have access to a user's time zone. This makes it difficult to extract a meaningful value for absolute times ("at 9pm", "tomorrow", etc.) -- instead it works best for relative times like "in 2 hours."

This is mostly fine, but some users would like "tomorrow" to be interpreted as "in 24 hours". Is there a simple way to do this?

**Comment by wanasit** [comment]
This is somewhat similar to #301. I'm updating the casual data parsing (today, tomorrow, ...) to also imply the same time as reference data (in `17bb16f`). Please check the next 2.x.x update.

Note: from reading your use-case, I'm not sure if this would really solve your problem completely. If you don't know what timezone of date you are parsing, you simply can't resolve it correctly. If you know or able to guess the timezone, checkout #327 discussion.

**Comment by lostfictions** [comment]
Thank you for the reply! That sounds perfect -- I'll look forward to the next 2.x.x update.
