### ISSUE TITLE
NaN for some dates after version 1.4.4

### ISSUE THREAD

**Issue by appins** [wanasit/chrono#338]
I used to be able to parse some dates, and now when I parse the same dates in version 1.4.6 I get NaN errors. These are the two dates that I am able to parse in 1.4.4 but not in 1.4.6.

`In  about 5 hours  (Monday, May 11, 2020 12:00 pm)`
`In  2 days  (Thursday, May 28, 2020 12:00 pm)`

I know that there is some ambiguity between 2 days and the date listed, but it used to parse to the absolute date listed rather than the relative one, which was a good solution. Now it parses to NaN for everything (ex: `result[0].start.get('day')` returns NaN).

**Comment by david-taggun** [comment]
Hi there - I'm seeing this too on `chrono-node: 1.4.8`

We're using it like this: `_chrono.parse('1 set wet weather', new Date());` I understand that it's not a valid date string, but Chrono still runs it 😀

I've attached the Chrono object that's causing the error => as this also produces an invalid date when calling `start.date()`
```
{
   "ref":"2020-10-23T04:19:39.946Z",
   "index":0,
   "text":"1 set",
   "tags":{
      "ESMonthNameLittleEndianParser":true
   },
   "start":{
      "knownValues":{
         "day":1
      },
      "impliedValues":{
         **"year":NaN,**
         "hour":12,
         "minute":0,
         "second":0,
         "millisecond":0
      }
   }
}
```

**Comment by wanasit** [comment]
Added some improvement. Could you please update to `2.1.9`?

**Comment by david-taggun** [comment]
Sorry mate - any chance we can get this added to 1.x.x? Because of the language support differences between 1 and 2 we're forced to stay a major version behind.

We tried going to version 2 but the accuracy of our system dropped when doing so.
