### ISSUE TITLE
Ability to add aliases to internal parsing configurations?

### ISSUE THREAD

**Issue by dsample** [wanasit/chrono#348]
I'd like to be able to associate additional aliases to the built-in parsing configurations. One example is that for a concise CLI, I'd like to associate `y` with `yesterday`, and `t` with `today`.

I've started doing this with a custom parser, but looking at [the code for the internal parser](https://github.com/wanasit/chrono/blob/master/src/locales/en/parsers/ENCasualDateParser.ts#L43-L47), I can't see an easy way to duplicate the logic, so I can only think that I have to do the date manipulation manually.

**Comment by wanasit** [comment]
I think I understand your difficulty, maybe standard casual date components (e.g. `today` , `yesterday`, ... ) should be refactored to more reusable functions. Let me do that.

However, to have those aliases, I still think you need a custom parser.

**Comment by wanasit** [comment]
Introduced `casualReferences` in c36e54a

```
import * as references from "./common/casualReferences";

...
return references.today(refDate) 
```

**Comment by dsample** [comment]
Thanks. Any recommendation for using `casualReferences` in a dependant system? the import statement wouldn't be relative. Just import `'chrono-node/src/common/casualReferences'` or does the library get published to a more pleasant path?
