### ISSUE TITLE
Identify whether the ParsedComponent is implied

### ISSUE THREAD

**Issue by pshah123** [wanasit/chrono#352]
In v1 with the separation of `knownValues` and `impliedValues`, it was possible to only collect known information which suits a lot of use cases (for example, if you have multiple sentences discussing the same event, and are trying to parse out only known information before relying on implied information). I'm wondering if this is possible with the v2 API?

**Comment by pshah123** [comment]
For anyone who comes across this: turns out these properties are still present, there's also a method "isCertain" that can be called if you parametrize your components.

**Comment by wanasit** [comment]
I also updated README file to include the function.
