### ISSUE TITLE
"2018 March 18" not parsed correctly

### ISSUE THREAD

**Issue by jakubriedl** [wanasit/chrono#353]
Hi, I have an issue with date `2018 March 18` parsed as `2021-03-18T20:18:00`.
Reproduction can be found here https://runkit.com/jakubriedl/5f94d523d51fb1001d681e35

The date was found in english article while doing NLP, don't know how much/in whose regions it is common way to write a date though. SugarJS (which fails on many different cases) managed to parse this correctly.

**Comment by wanasit** [comment]
Fixed on 76d493b. Please wait for the next patched version.

**Comment by jakubriedl** [comment]
Thanks for super quick fix. Much appreciated.
