### ISSUE TITLE
Simple form relative time like "-1 days"

### ISSUE THREAD

**Issue by ajmas** [wanasit/chrono#354]
This package is useful, though I am wondering whether there would be any interest in supporting other expressions, such as:

  - `-1 days`
  - `+2 days`

My current approach is combine this package with [relative-time-parser](https://www.npmjs.com/package/relative-time-parser), such when chrono doesn't support the expression then I try the other package to see it i can parse.

Having the combined functionality in one package would be useful

**Comment by wanasit** [comment]
Hello @ajmas. Chrono does have support for the format (e.g. see [our testcases](https://github.com/wanasit/chrono/blob/master/test/en/en_time_units_casual_relative.test.ts#L71)).

You could do:
```
chrono.parseData('+2 days')
chrono.parseData('+2 days', new Date(2020, 11-1, 22)) // with a reference data
```
