### ISSUE TITLE
Lets meet in Jan

### ISSUE THREAD

**Issue by g-g-n** [wanasit/chrono#355]
Sentence like "Lets meet in Jan" does not seem to work for me. 

For "Lets meet next year" I expect to get a date of 01-Jan-2021 but I get the today's date and month for next year. 

Am I missing something ?

**Comment by wanasit** [comment]
Thank you for letting me know. And sorry for my slow reply.

 `Lets meet in January` actually work, but `Lets meet in Jan` had similar problem about short month names reported in #357.
This should already be fixed.

"Lets meet next year" is different. `Next <something>` is interpret as `+<something>` to the reference time. I won't necessary started in January.

```
const result = chrono.parse("Lets meet next year", new Date(2020, 11 -1, 22))[0]

> result.start.get('year') // 2021
> result.start.get('month') // 11
> result.start.isCertain('month') // false
```
