### ISSUE TITLE
Aggressive timezone parsing produces many incorrect results

### ISSUE THREAD

**Issue by lostfictions** [wanasit/chrono#360]
[`ExtractTimezoneAbbrRefiner`](https://github.com/wanasit/chrono/blob/master/src/common/refiners/ExtractTimezoneAbbrRefiner.ts) interprets valid words in many languages as timezones, leading to incorrect parsing.

Some examples:

```
> chrono.parseDate('in 1 hour eggs and milk')
2020-11-14T02:35:28.000Z   -- correct
> chrono.parseDate('in 1 hour get eggs and milk')
2020-11-13T17:35:32.000Z   -- "get" interpreted as timezone
> chrono.parseDate('in 1 hour eat dinner with john')
2020-11-13T18:38:42.000Z   -- "eat" interpreted as timezone 
> chrono.parseDate('in 1 hour wet clothes into dryer')
2020-11-13T21:39:20.000Z   -- "wet" interpreted as timezone
```
Other languages are also subject to errors:

```
> chrono.fr.parseDate('dans 1 heure mon anniversaire')
2020-11-14T02:40:32.000Z   -- no problem
> chrono.fr.parseDate('dans 1 heure cest mon anniversaire')  -- eg. casual orthography in french
2020-11-13T19:40:50.000Z   -- "cest" interpreted as timezone
```

As a first suggestion, I think timezone parsing should definitely not be applied to relative times. As far as I know, regardless of language it never makes sense to apply a timezone to a relative time -- "in one hour pacific time" is not a thing people can mean; one hour just means one hour.

I would happily submit a PR for this, but unfortunately it looks tricky to achieve given the current structure of the code, where all refiners are always applied regardless of parser. It seems like this would need to change for this fix to be achievable, but I think it's important -- otherwise many sentences will continue to be incorrectly parsed. How would you like to proceed?

---

Beyond the obvious scenario of relative times described above, I think this issue can still arise even when specifying absolute times -- and the solution may be more tricky. As a simple example, "At 1pm get eggs and milk" is a similar case where parsing would be incorrectly applied. Here are some potential solutions I can think of:

- Only parse uppercase timezones. For example, "at 1pm GET eggs and milk" would be parsed in the GET timezone but "1pm get" would not. This seems potentially brittle -- there are many reasons input might be in uppercase, so it may not reliably disambiguate correctly.
- Make timezone parsing opt-in. This would ensure no ambiguities are possible, but would require the developer to understand the tradeoffs based on their expected use case.
- Make timezone parsing locale-sensitive. I think this might make the most sense for "casual" parsing, even though it would technically mean certain timezones would not be parsed. For example, an English timezone parser could omit WET, GET, and EAT and other ambiguous timezones **unless** they are in an unambiguous position, like the end of the input. (For example, "at 1pm get eggs" would not parse "get" at a timezone, but "eggs at 1pm get" _would_ parse "get" as a timezone.) For most "casual" purposes this seems like it would provide the correct result more frequently.

**Comment by wanasit** [comment]
Thank you for you thoughtful comment on the problem. 

I agree with several of your points:
* We should never apply the timezone extraction for relative times. And it's currently not easy to do so.
* Making timezone parsing uppercase is a good idea (making locale-sensitive is also reasonable). However, I'd like to want to keep the timezone detection on default.


Please let me think about this a bit more.

**Comment by TimothyJones** [comment]
I've also hit this - is it possible to turn off the timezone parsing completely by configuration?
