### ISSUE TITLE
Only extract date, ignore time

### ISSUE THREAD

**Issue by ethanyu94** [wanasit/chrono#363]
For example string "Thursday 9AM", is there any way to configure the parser to only return the "Thursday" part and ignore the time? I am trying to find and highlight dates in my application, but not times.

**Comment by wanasit** [comment]
hmm. Parsing date only and not touching time at all is not simple. 

You could simply remove `ENTimeExpressionParser`:
```
const custom = chrono.en.casual.clone();
custom.parsers = custom.parsers.filter((p) => !(p instanceof ENTimeExpressionParser));

custom.parse("Thursday 9AM")
// => [ {text: "Thursday", ...} ]
```
However, what do you want to do about these formats?:
* ISO standard e.g. `1994-11-05T08:15:30+11:30`
* Time ago e.g. `2 hours ago`
