### ISSUE TITLE
Timezone-induced test failures on CI

### ISSUE THREAD

**Issue by lostfictions** [wanasit/chrono#364]
When updating #361, I experienced an odd issue -- a few tests were failing on master (not my own branch!) for no clear reason. Here's the summary:

> Summary of all failing tests
>  FAIL  test/en/en_relative.test.ts (9.746 s)
>   ● Test - Relative date components' certainty
> 
>     expect(received).toBe(expected) // Object.is equality
> 
>     Expected: -240
>     Received: -300
> 
>       155 |         expect(result.start.get("day")).toBe(7);
>       156 |         expect(result.start.get("hour")).toBe(12);
>     > 157 |         expect(result.start.get("timezoneOffset")).toBe(refDate.getTimezoneOffset() * -1);
>           |                                                    ^
>       158 | 
>       159 |         expect(result.start.isCertain("year")).toBe(true);
>       160 |         expect(result.start.isCertain("month")).toBe(true);
> 
>       at test/en/en_relative.test.ts:157:52
>       at Object.<anonymous> (test/en/en_relative.test.ts:151:5)
> 
>   ● Test - Relative date components' certainty and imply timezone
> 
>     Expected date to be: Mon Nov 30 2020 11:00:00 GMT-0500 (GMT-05:00) Received: Sun Nov 29 2020 11:00:00 GMT-0500 (GMT-05:00) ([ParsingResult {index: 0, text: 'tomorrow at 5pm', ...}])
> 
>       186 |         result.start.imply("timezoneOffset", 60);
>       187 | 
>     > 188 |         expect(result).toBeDate(new Date("Sun Dec 1 2020 1:00:00 GMT+0900 (Japan Standard Time)"));
>           |                        ^
>       189 |         expect(result).toBeDate(new Date("Sun Nov 30 2020 17:00:00 GMT+0100"));
>       190 |     }
>       191 | 
> 
>       at Object.<anonymous> (test/en/en_relative.test.ts:188:24)
> 

This is current `master`, which is at commit [`6daa27d`](https://github.com/wanasit/chrono/commit/6daa27d0fae43a12c42d43c1bab2d79d1d4ed570). I'm on Node `v14.15.1`.

Most oddly, I rebased PR #361 on top of that commit, and didn't make any changes that should affect tests, but they pass on Travis instead of failing.

**Comment by benaubin** [comment]
Hmm... feel like this could be related to timezones

**Comment by ptz0n** [comment]
Yep, fixed in #368.

**Comment by lostfictions** [comment]
Great! Closing, thanks :)

**Comment by lostfictions** [comment]
Oh wait, misread -- I guess the second one remains to be fixed? Reopening for now.

**Comment by wanasit** [comment]
hey~ happy new year! sorry for my slow reply.

@lostfictions what is you timezone? I guess it's GMT-05:00 now, but GMT-04:00 in November.

I think I know what happened was `Sun Nov 29 2020 13:24:13 GMT+0900 (Japan Standard Time)` is absolute equivalent to `Sun Nov 29 2020 00:24:13 GMT-0400` (in your timezone).

There is an edge case check in tomorrow() or assignNextDay() to not increase the day when the ref time is too close to the midnight:
https://github.com/wanasit/chrono/blob/master/src/utils/dayjs.ts#L8

**Comment by wanasit** [comment]
With `refDate` as normal `Date` object, the refDate's timezone information will be lost and we cannot really calculate the precise relative time without assuming it's the same timezone as the system. Maybe in the future major release we should let people pass refTimezone or refDate as string.

For now, I am thinking we should remove that close to mid-night checking logic (minor release 2.2+) sometime this weekend. I don't really think that logic is that helpful anyway. 

Please let me know what you think.

**Comment by wanasit** [comment]
Removed that in d898037

**Comment by gabegorelick** [comment]
Still see a failing test when running `master` locally related to this:

```
Summary of all failing tests
 FAIL  test/en/en_relative.test.ts
  ● Test - Relative date components' certainty and imply timezone

    Expected date to be: Mon Nov 30 2020 11:00:00 GMT-0500 (Eastern Standard Time) Received: Sun Nov 29 2020 11:00:00 GMT-0500 (Eastern Standard Time) ([ParsingResult {index: 0, text: 'tomorrow at 5pm', ...}])

      195 |         result.start.imply("timezoneOffset", 60);
      196 |
    > 197 |         expect(result).toBeDate(new Date("Sun Dec 1 2020 1:00:00 GMT+0900 (Japan Standard Time)"));
          |                        ^
      198 |         expect(result).toBeDate(new Date("Sun Nov 30 2020 17:00:00 GMT+0100"));
      199 |     }
      200 |

      at Object.<anonymous> (test/en/en_relative.test.ts:197:24)
```

Running with `TZ=UTC` fixes the issue. 

If it's just an issue with the tests, perhaps `TZ=UTC` should be set in the npm script?
