### ISSUE TITLE
Feature: Updated and more comprehensive documentation

### ISSUE THREAD

**Issue by KevinNovak** [wanasit/chrono#367]
I [recently had an issue](https://github.com/wanasit/chrono/issues/75#issuecomment-751830717) where I needed Chrono to parse English, but in a DD/MM/YYYY format, which is not the default.

The solution was to use the `littleEndian` configuration option, which I only found from experimenting with the code, and is not mentioned anywhere in the documentation. In fact, I don't see anything documented about the `createConfiguration()` methods.

This is just one example, but I think in general the documentation could use a look over, and maybe even creating a dedicated documentation site like other libraries, would be extremely helpful!

Some documentation tools that might be worth looking into:

- [GitBook](https://www.gitbook.com/) ([example](https://docs.gitbook.com/))
- [ESDoc](https://esdoc.org/) ([example](https://moment.github.io/luxon/docs/))
- [Read the Docs](https://readthedocs.org/) ([example](https://bootstrap-datepicker.readthedocs.io/en/latest/))

**Comment by benaubin** [comment]
@wanasit Since you just switched over to Typescript, maybe we can make use of Typedoc for configuration options?

**Comment by wanasit** [comment]
Thank you for your suggestion! I just back from holiday and I will look into those options when I have time.
Please feel free to try that and create MR without me too.

**Comment by wanasit** [comment]
Update. I have tried a few things. I think:
- Chrono will host its documentation as Github Pages website (e.g. http://wanasit.github.io/chrono/ from `/docs` folder)
  - It's easy and popular. I could find a lot of examples.  
  - Hosting them in Read-the-docs or Gitbook seem overkill.
- The documentation will be generated via [Typedoc](https://typedoc.org/) as @benaubin suggested. 
  - Generating the document directly from the code comment and type declaration should be the easier to maintain/update comparing to writing a separated md or reStructuredText. 

I am trying to set things up on `doc-prototype` branch. 
Please feel free to give me early feedback.

**Comment by KevinNovak** [comment]
Looks great so far, I would suggest adding descriptions to each of the items (classes, methods), and maybe examples where appropriate.

**Comment by wanasit** [comment]
I have updated the document for some classes easily visible in index.ts, but still, need to continue refining that.
For now, I'm closing this issue.

**Comment by KevinNovak** [comment]
Thanks, it's looking great! Appreciate the work and it will definitely help others as well.

**Comment by KevinNovak** [comment]
I know this is a closed issue, but should we link to http://wanasit.github.io/chrono/ in the README? Also GitHub lets you set a "website" for the repo we could link to the documentation.
