### ISSUE TITLE
Recommended way to deal with the included parsers and refiners

### ISSUE THREAD

**Issue by ignaciodolan** [wanasit/chrono#370]
Hi,
I was wondering what is the recommended way to deal with current parsers and refiners as I have an issue with the  [UnlikelyFormatFilter](https://github.com/wanasit/chrono/blob/master/src/common/refiners/UnlikelyFormatFilter.ts).
The thing is that i want to get a result when writing dates like: `12.07` and its currently being removed by the UnlikelyFormatFilter as its regex for checking if its valid (`/^\d*(\.\d*)?$/`) is catching this result.
I can remove it by filtering out the refiner when customising it but i was wondering if there was another approach. 
Thanks!

**Comment by wanasit** [comment]
Hello. How about just remove it? I answered a similar question once a while ago.
https://github.com/wanasit/chrono/issues/343

**Comment by ignaciodolan** [comment]
@wanasit alright thanks for the reply, will do that, do you think it would be valuable to add this as part of the README? I wouldnt mind doing it.
