### ISSUE TITLE
False positives with decimals such as "at 6.5 kilograms".

### ISSUE THREAD

**Issue by KevinNovak** [wanasit/chrono#374]
Chrono is recognizing "at 6.5 kilograms" as 6:05 AM. For reference, I am using the strict English parser. I believe this is because Chrono simply looks for a number between 0-59 in this case, but does not require 0 padding for numbers 0-9. I would expect 6.05 to trigger a time, but not 6.5.

**Comment by meister03** [comment]
Having the same problem ;(

**Comment by wanasit** [comment]
This should be fixed in 1d949a2
