### ISSUE TITLE
How can I give the parsed Date from the message in milliseconds since 1960 like the Date.now() format?

### ISSUE THREAD

**Issue by meister03** [wanasit/chrono#375]
```js
 let date = chrono.parseDate("An appointment on Sep 12-13");
 console.log(new Date(date).toString());   //Sat Sep 12 2020 12:00:00 
 ```
 This should give the next year not 2020. I know that the parser already give the date. But I wanted to show you a unterstandable time, which is one year ago :(

**Comment by wanasit** [comment]
Sorry. I don't understand the question. 

The example code that you gave was not a bug. The input doesn't specify any year, just "Sep 12", so it guesses the closest one.
* Change reference date: e.g. `chrono.parseDate("An appointment on Sep 12-13", new Date(2021, 7-1, 1))` 
* Use `forwardDate` options if only what the library to guess forward into the future. e.g. `chrono.parseDate("An appointment on Sep 12-13", null, {forwardDate: true})` 

> How can I give the parsed Date from the message in milliseconds since 1960 like the Date.now() format?

So you want the timestamp (it's started at 1970-01-01, not 1960)? 
Try `getTime()` function.
 
```
let date = chrono.parseDate("An appointment on Sep 12-13");

// The `date` is already Javascript Date object
console.log(date.getTime());
```

**Comment by meister03** [comment]
How can I get the Time for a another Timezone?
like my Timezone is now: America/New York
Its definitely a String.
So how will I get the correct time and not the local one?
Thanks in Advance!
