### ISSUE TITLE
TypeError: chrono_node__WEBPACK_IMPORTED_MODULE_18___default.a is undefined

### ISSUE THREAD

**Issue by cnicodeme** [wanasit/chrono#376]
Hi,

I'm not sure what's happening, but when trying to do call `parseDate` from Chrono, I get the following error:

> TypeError: chrono_node__WEBPACK_IMPORTED_MODULE_18___default.a is undefined

Chrono is imported via `import chrono from 'chrono-node'` and I have installed the version 2.2.0 via NPM.
There is no other variable named chrono that could affect the current scope, or not a home package with a similar name that could conflict.

Calling just `console.log(chrone)` returns undefined.

**Comment by wanasit** [comment]
Have you already try removing the `node_modules` and run `npm install` to reinstall everything again?

**Comment by cnicodeme** [comment]
Hi @wanasit.

I did what you asked but unfortunately I still have the same issue.

If it helps, the issue is caused by this line:

`const parsedDate = chrono.parseDate(value, new Date(), { forwardDate: true })`

For information, `value` is "monday".

**Comment by cnicodeme** [comment]
I've been digging a bit more.

I tried downgrading Chrono-node version by version and testing. I always have the same issue.
I could go as low a v2.1.10, since 2.1.9 is not available on NPM repository.

Then, I create a new blank project using VueJS (v2) via Vue-cli, installed Chrono, and added the following code :

```
methods: {
    getDate () {
      return chrono.parseDate('monday')
    }
  }
```

In the "Home.vue" of the default sample from vue-cli.

I still have the same error.

I'll continue to investigate, but hopefully now, you have something that you can reproduce.

In case it works on your end, here's the `package.json` file from my "test" Vue installation:

```
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "chrono-node": "^2.2.1",
    "core-js": "^3.6.5",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-standard": "^5.1.2",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^6.2.2",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "vue-template-compiler": "^2.6.11"
  }
}

```

**Comment by cnicodeme** [comment]
Ok, running more tests, it yield that the following doesn't work : 

```
import { chrono } from 'chrono-node' // undefined
import { Chrono } from 'chrono-node' // Import the Chrono class, which has to be instantiated
import chrono from 'chrono-node' // undefined
import Chrono from 'chrono-node' // undefined
```

But doing the following works : 

`import { parseDate } from 'chrono-mode'`

This makes sense when we look at how the documentation for Chrono ask to import Chrono:

`import * as chrono from 'chrono-node';`

* is mapped to chrono, which will contains the exported functions, such as `parseDate`.

All in all, there is not a real problem, but maybe having a way to explain how not to import "*" from the project could be a nice thing?

I'll let you make the decision here, but in case you have the same errors from other people, you'll know what it's about ;)

Good luck!

(I'll keep the issue open and let you decide on what to do).

**Comment by wanasit** [comment]
Thank you for letting me know. I'm sorry for your experience. 

I will try to find a better way to explain how the importing should work, but I afraid I may not be able to work on that anytime soon. (any contribution is welcome)

**Comment by cnicodeme** [comment]
No problem! I fully understand :) Good luck!
