### ISSUE TITLE
Where can I add a timezone?

### ISSUE THREAD

**Issue by meister03** [wanasit/chrono#379]
I want that when the user, has a another timezone, that is parses the ms since 1970 on that timezone.

I have a Timwezone string: America/New_York
and with this String. I want to parse the date. Is it poosible?

**Comment by meister03** [comment]
```js
let parsedtime = chrono.parseDate("Appointment at 12pm"+ ` in ${user.timezone || "America/New_York"}`, null, {forwardDate: true})
```
That was the option, I tried, passing the timezone in a string. Isnt there a system option for the function, where you can pass the timezone?

**Comment by meister03** [comment]
```
let checkfortimezone =  new Date(DateTime.fromObject({zone: usertz.timezone}))
let parsedtime = chrono.parseDate(newmessage.content, checkfortimezone, {forwardDate: true});
```
The ref date does not seem to work. It outputs me a invalid day. DateTime gets the local Time of the Timezone

**Comment by lvillacin** [comment]
I'd like to add that I also have this problem. The solution that I have come up with is to get the offset (eg -08:00) using offset from "America/Los_Angeles" and manually adding that to the parsed string. However I have a weird timezone problem when the situation is something like this:

User's timezone: Asia/Manila
Server timezone: UTC
Parse: "tomorrow"

Expected behavior: chrono provides tomorrow the next day in Asia/Manila Time
Actual behavior: chrono provides the next day but since UTC is still in the previous date (in user's POV), it's tomorrow is still the same day to the user (in their timezone)

**Comment by meister03** [comment]
> I'd like to add that I also have this problem. The solution that I have come up with is to get the offset (eg -08:00) using offset from "America/Los_Angeles" and manually adding that to the parsed string. However I have a weird timezone problem when the situation is something like this:
> 
> User's timezone: Asia/Manila
> Server timezone: UTC
> Parse: "tomorrow"
> 
> Expected behavior: chrono provides tomorrow the next day in Asia/Manila Time
> Actual behavior: chrono provides the next day but since UTC is still a day late in user's POV, the output "tomorrow" is still the same day to the user (in their timezone)

How do I get the offset of a specific timezone?

**Comment by lvillacin** [comment]
@meister03 I used moment and did this:
```
const offSet = moment.tz(timezone).toLocaleString().slice(-5)
```
Pretty crude but was able to get the offset in the format i needed.

**Comment by meister03** [comment]
> @meister03 I used moment and did this:
> 
> ```js
> const offSet = moment.tz(timezone).toLocaleString().slice(-5)
> //+0800
> ```
> 
> Pretty crude but was able to get the offset in the format i needed.
yes good, used this too. the problem is the DST.

**Comment by lvillacin** [comment]
@meister03 sorry i didn't specify well, i used moment-timezone and passed IANA timezone codes

**Comment by benaubin** [comment]
Hi there! Chrono recognizes this list of three-letter timezones: https://github.com/wanasit/chrono/blob/344026e9a08f6956048691de3322f093a45daed5/src/common/refiners/ExtractTimezoneAbbrRefiner.ts

For the use case you describe, I recommend adding a post-processing step such as the following to imply the user's time zone:

https://github.com/lukec11/Jonathan/blob/46dfb254fd100850c36de6d78db734f7a88e66c6/src/index.js#L111-L115

Probably would be a good idea to document that flow and improve the API.

**Comment by meister03** [comment]
Thx, but where do I pass the offset in the refDate?

**Comment by wanasit** [comment]
Adding to @benaubin answer. 
If you know the timezone where the result should be in.
```
let result = chrono.parse("Appointment at 12pm", null, {forwardDate: true})[0]
result.imply('timezone', xxx)

// result.date() => 12pm on the xxx timezone
```

> https://github.com/lukec11/Jonathan/blob/46dfb254fd100850c36de6d78db734f7a88e66c6/src/index.js#L111-L115
> Probably would be a good idea to document that flow and improve the API.

@benaubin yeah. this is not the first time the ref timezone is mentioned. I think we should improve the API. Thanks for showing me how people are using it.

**Comment by meister03** [comment]
> Adding to @benaubin answer.
> If you know the timezone where the result should be in.
> 
> ```
> let result = chrono.parse("Appointment at 12pm", null, {forwardDate: true})[0]
> result.imply('timezoneOffset', xxx)
> 
> // result.date() => 12pm on the xxx timezone
> ```
> 
> > https://github.com/lukec11/Jonathan/blob/46dfb254fd100850c36de6d78db734f7a88e66c6/src/index.js#L111-L115
> > Probably would be a good idea to document that flow and improve the API.
> 
> @benaubin yeah. this is not the first time the ref timezone is mentioned. I think we should improve the API. Thanks for showing me how people are using it.

Perfect ❤️ . I will try it asap
