### ISSUE TITLE
How to improve parsing performance?

### ISSUE THREAD

**Issue by geo-systems** [wanasit/chrono#380]
Hi there,

I need to write a program, which parses many dates in different formats.

I've encountered a performance issue with `chrono`. Here's a benchmark, which demonstrates the issues:

```js
const chrono = require("chrono-node")
let max = 100000;

console.time("chrono parsing");
for (let i = 0; i < max; i++) {
  chrono.en.strict.parseDate("11/12/2021");
}
console.timeEnd("chrono parsing");

console.time("native parsing");
for (let i = 0; i < max; i++) {
  new Date("11/12/2021");
}
console.timeEnd("native parsing");
``` 

The output is:

```
chrono parsing: 34.235s
native parsing: 62.26ms
```

I understand that `chrono` does much more than the native parsing and it's understandable that it's slower. However 500 times slower seems a bit too much.

Is there a way to speed up `chrono`? Can I disable some patterns or locales to speed it up?

**Comment by wanasit** [comment]
Hello. Thanks for reporting this. This could be improved by reducing the backtracking as in #382, but I afraid it won't be as fast as native javascript.

> However 500 times slower seems a bit too much.

I am afraid it is not. I believe [the Date constructor is native](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toSource) (imagine optimized C/C++ routine built into Javascript engine) while the Chrono parsing is a normal Javascript code run on top of the engine.

Do you have any specific parsing latency number to achive or any time-critical use-case you have in mind?

**Comment by geo-systems** [comment]
Thanks for looking into this!

For 100K records (as in the benchmark), up to 10 seconds would be acceptable. I'm parsing a few million records and with the current performance the user would have to wait 20-30 minutes.

I've also conducted benchmark with another library called [Sugar JS](https://sugarjs.com/):

```js
const chrono = require("chrono-node")
const sugar = require("sugar")

let max = 100000;

console.time("chrono parsing");
for (let i = 0; i < max; i++) {
  chrono.en.strict.parseDate("11/12/2021");
}
console.timeEnd("chrono parsing");

console.time("sugar parsing");
for (let i = 0; i < max; i++) {
  sugar.Date.create('11/11/2021');
}
console.timeEnd("sugar parsing");

console.time("native parsing");
for (let i = 0; i < max; i++) {
  new Date("11/12/2021");
}
console.timeEnd("native parsing");
```

The result shows that Sugar JS is about 15 times faster:

```
chrono parsing: 35.917s
sugar parsing: 2.123s
native parsing: 65.936ms
```

My current approach is to attempt parsing with `Sugar JS` first. I only try with `Chrono JS` if Sugar JS fails. It works well for most scenarios, but I would prefer to use a single library.

**Comment by wanasit** [comment]
The version `v2.2.4` has some performance improvement from caching regex compile. It show significant speed improvement on my machine. Could you try the new version?

**Comment by geo-systems** [comment]
Thanks @wanasit ,

Yes, that's more than twice faster! However, it's still significantly slower than `Sugar JS`:

```
# Parsing 100K records:
chrono parsing: 15.530s (was 35.917s before the optimisations)
sugar parsing: 2.018s
native parsing: 64.81ms
```

**Comment by wanasit** [comment]
Version v2.2.5 has some performance improvement from avoid using dayjs. Could you try again?

**Comment by geo-systems** [comment]
Thanks @wanasit ,

Indeed, that's much faster!:

```
# Parsing 100K records:
chrono parsing: 4.527s
sugar parsing: 2.172s
native parsing: 66.073ms
```

**Comment by wanasit** [comment]
@geo-systems If you try the latest version, there should be a bit more of performance gain. 
Hope the current performance is enough for your use-case.

To make it even faster, my profiler shows that, Chrono is spending most time in **SlashDateFormatParser** as well as **AbstractTimeExpressionParser** (ENTimeExpressionParser). The later make senses each number (e.g. `[11] 12/2021`) could be time components and it was spending time checking. 

You could make Chrono twice faster in the benchmark by simply removing ENTimeExpressionParser (e.g. if you know you parse only date and don't need time parsing at all).

However, for now, I don't think further tuning performance just for one pattern make senses. 
So, I'm closing this issue now.
