### ISSUE TITLE
Building typescript project that includes Chrono 2.2.2 fails

### ISSUE THREAD

**Issue by KevinNovak** [wanasit/chrono#381]
When I build my TypeScript project that includes Chrono 2.2.2 I get the following build failure:

![image](https://user-images.githubusercontent.com/11231402/110248412-f92b5a80-7f3e-11eb-8d9a-177a5ef9df34.png)

When I revert to 2.2.1 it builds successfully.

It seems something between 2.2.1 and 2.2.2 has caused "DebugHandler" to no longer be exported?

![image](https://user-images.githubusercontent.com/11231402/110248560-cf266800-7f3f-11eb-8c2f-a8124d7ec951.png)

**Comment by wanasit** [comment]
Thank you for reporting the problem. Could you please try again with 2.2.3?

**Comment by KevinNovak** [comment]
2.2.3 fixed the build, thanks!
