### ISSUE TITLE
Odd behavior with dash-separated numbers

### ISSUE THREAD

**Issue by KevinNovak** [wanasit/chrono#384]
I'm seeing a weird behavior with dash-separated numbers, for example:

"1-2-3" --> 1:00 AM to 2:00 AM, with a UTC offset of -3 hours
"4-5-6" --> 4:00 AM to 5:00 AM, with a UTC offset of -6 hours
"3-2-1" --> 3:00 AM to 2:00 AM, with a UTC offset of -1 hours

Maybe this is working as intended and is just a weird edge case, just thought I'd share.

I'm using Chrono in a chat application to recognize times that users type, and this combined with the lack of boundary separation (#383) can cause some false positives if a user's message has text like this somewhere in the message.

**Comment by wanasit** [comment]
This is fixed in 053cc8f (`2.2.6`)
