### ISSUE TITLE
Support numbers separated by spaces

### ISSUE THREAD

**Issue by pradyuman** [wanasit/chrono#386]
The following strings succeed:
```
12-29-1996
29-12-1996
```

However, the following strings fail to parse:
```
12 29 1996
29 12 1996
```

Is it possible to support numbers separated by spaces?

**Comment by wanasit** [comment]
I don't think we should support that by default. The false-positive / incorrect parsing would too often.

Could you create [a custom parser](https://github.com/wanasit/chrono#parser) for your use-case? I recommend you look at the current SlashDateFormatParser.
