### ISSUE TITLE
7-730 Combination giving end time null

### ISSUE THREAD

**Issue by sathishkumars92** [wanasit/chrono#387]
Hi we love chrono and it's amazing and works for most cases but this issue with "-" followed by time not working

For eg:
**7-730** giving start 7am and end null for as **7-730a** works it gives start time 730am and end time 8am. Same way **730-8** works give correct start and end time.

**Comment by wanasit** [comment]
As of `2.2.6`:
* the input "7-730" or "730-8" won't return any result.
* the input "7-730a" does give a result (start time 7:00am and 7:30am), but I'm not sure if we infer "a" as "am".

@KevinNovak This is somewhat related to #384. Any comment?
