### ISSUE TITLE
How can I build chrono for browser?

### ISSUE THREAD

**Issue by slavaGanzin** [wanasit/chrono#390]
Hello chrono is great! But i used it only in node.

So how to build browser bundle? I've tried 
```
1. npm run build
2. webpack ./dist/chrono.js --mode development
```

Nothing really happening.Is it intended to work in browser?

**Comment by wanasit** [comment]
Hello. Sorry for my slow reply. 

The current project is designed to be installed by npm, because I think that how most people do it these days. But I will think about how to make that available.

Your script doesn't work because you need webpack to bundle chrono with "library" option. 
(see https://webpack.js.org/guides/author-libraries/)

e.g. create this `webpack.conf.js`
```
const path = require("path");

module.exports = {
    entry: "./dist/index.js",
    output: {
        path: path.resolve(__dirname, "bundle"),
        filename: "chrono.js",
        library: "chrono",
    },
};
```
Then, run your command:
```
npm run build
webpack
```

Then, you should be able to do:
```html
<script src="./bundle/chrono.js"></script>
<script>
chrono.parse("xx");
</script>
```

**Comment by agamm** [comment]
@wanasit What is the contents of `dist/index.js`?

**Comment by Pranoy1c** [comment]
For anyone still looking, here's how I did it:

1. Navigate to your project directory:
 
     cd /Volumes/500GB_extre/Order2
 
 2. Install chrono-node:
 
     npm install --save chrono-node
 
 3. Globally install browserify:
 
     npm install -g browserify
 
 4. Create forbrowserify.js, sort of a configuration file which will bundle everything from chrono-node and make available to the browser window:
 
 ```
var chrono = require('chrono-node');
 global.window.chrono = chrono;
```
 
 5. Create the final bundle.js using browserify:

     browserify forbrowserify.js -o bundle.js
 
 6. You will now have the final bundle.js available that you need to include in your website:
 
```
 <script src="./bundle.js"></script>
 
 <script>
     const referenceDate = new Date();
     let parsed = window.chrono.parse('An appointment on Sunday from 2:15pm to 2:45pm', referenceDate, { forwardDate: true })[0];
     console.log(`Start: ${parsed.start.date()}, End: ${parsed.end.date()}`);
 </script>
```
