### ISSUE TITLE
Keyword + Timezone not working

### ISSUE THREAD

**Issue by healzer** [wanasit/chrono#392]
I love this library, it's amazing!

There is one thing that's bugging me:
when I use a keyword with a timezone it doesn't work (timezone not being considered).

```
parseDate("april 22 EST")   // works (if explicit date provided)
parseDate("1pm EST")        // works (if time provided)
parseDate("today 1pm EST")  // works (if time provided)

parseDate("today EST")      // does not work (without time)
parseDate("tomorrow EST")   // does not work  (without time)
parseDate("next week EST")  // does not work  (without time)
```

Is there anything we can do about this?
If no time is provided it could at least use the current time, while still consider the provided timezone.

Thank you! <3

**Comment by wanasit** [comment]
Added some improvement in 77fbd83.

Your example should work:
```
parseDate("today EST") 
parseDate("tomorrow EST")
parseDate("next week EST") 
```

However, when for "relative time" cases, not be able to handle timezone correctly is a known limitation.
```
parseDate("in 3 hours") // is "in 3 hours"
parseDate("in 3 hours GMT") // is also just "in 3 hours"
```
Ref: #385, #360
