### ISSUE TITLE
Support CE and BCE as synonyms for AD and BC, respectively

### ISSUE THREAD

**Issue by gabegorelick** [wanasit/chrono#394]
In English locales (can't speak for any others), CE and BCE are fairly common synonyms for AD and BC, respectively. See https://en.wikipedia.org/wiki/Common_Era.

> Common Era (CE) is one of the year notations used for the Gregorian calendar (and its predecessor, the Julian calendar), the world's most widely used calendar era. Before the Common Era (BCE) is the era before CE. BCE and CE are alternatives to the Dionysian BC and AD notations, respectively. The Dionysian era distinguishes eras using the notations BC ("Before Christ") and AD (Latin: Anno Domini, in [the] year of [the] Lord).[1] The two notation systems are numerically equivalent: "2021 CE" and "AD 2021" each describe the current year; "400 BCE" and "400 BC" are each the same year.

Chrono doesn't seem to handle it:
https://github.com/wanasit/chrono/blob/b6140ec17996fec84c790891ecbfd8b7d44fbb5b/src/locales/en/constants.ts#L201-L222

Failing tests:
```js
testSingleCase(chrono, "10 August 234 BCE", new Date(2012, 7, 10), (result) => {
        expect(result.index).toBe(0);
        expect(result.text).toBe("10 August 234 BCE"); // fails since text is `10 August 234`

        expect(result.start).not.toBeNull();
        expect(result.start.get("year")).toBe(-234);
        expect(result.start.get("month")).toBe(8);
        expect(result.start.get("day")).toBe(10);

        expect(result.start).toBeDate(new Date(-234, 8 - 1, 10, 12));
});
    
testSingleCase(chrono, "10 August 88 CE", new Date(2012, 7, 10), (result) => {
        expect(result.index).toBe(0);
        expect(result.text).toBe("10 August 88 CE");

        expect(result.start).not.toBeNull();
        expect(result.start.get("year")).toBe(88);
        expect(result.start.get("month")).toBe(8);
        expect(result.start.get("day")).toBe(10);

        const resultDate = result.start.date();
        const expectDate = new Date(88, 8 - 1, 10, 12);
        expectDate.setFullYear(88);
        expect(expectDate.getTime()).toBeCloseTo(resultDate.getTime());
});
```

**Comment by wanasit** [comment]
Added in cb8d48d.
