### ISSUE TITLE
Parsing error "for" vs "in"

### ISSUE THREAD

**Issue by dweberlj** [wanasit/chrono#40]
When parsing "set a timer for 2 minutes" will fail but "set a timer in 2 minutes" will pass.  Any idea why the word "for" vs "in" would cause the parser to give different results?

**Comment by BtM909** [comment]
`for` would imply a duration, whereas `in` talks about a specific time (in the future). Do you want to have the same result or should `for` give a duration from now until 2 minutes in the future?
