### ISSUE TITLE
Zh chinese locales in new version

### ISSUE THREAD

**Issue by arthurtalkgoal** [wanasit/chrono#413]
I found that there is zh translation (chinese) in the earlier commits but it is missing in the new version. 

Can I know that what is the challenge or any one is working on it? I am happy to help on it.

**Comment by wanasit** [comment]
Hello. Sorry for my slow reply. I've recently merge #417 (from @ DingWeizhe) and publish the zh-hant support in v2.3.5.

You could try `chrono.zh.hant`. 
Please feel free to send us MRs if you need to extend them.
