### ISSUE TITLE
How do I reformat the output of `parseDate`?

### ISSUE THREAD

**Issue by aentan** [wanasit/chrono#42]
I want to turn:

`Fri Aug 24 2012 12:00:00 GMT+0700 (ICT)`

into

`August 24, 2012`

for example.

**Comment by wanasit** [comment]
Sorry for super slow response.

Chrono doesn't support formatting `Date` object to string. There is a nice library call [moment.js](http://momentjs.com/)

```
var date = chrono.parseDate(' Fri Aug 24 2012 12:00:00 GMT+0700 (ICT) ');
moment(date).format('MMMM DD, YYYY');
// August 24, 2012
```
