### ISSUE TITLE
Unusual pattern recognition on timezone offsets

### ISSUE THREAD

**Issue by ghost** [wanasit/chrono#420]
Node session with `chrono-node` v2.3.4:

```
Welcome to Node.js v12.22.5.
Type ".help" for more information.
> chrono = require("chrono-node")
...
```

This seems OK:
```
> chrono.parse("2200-12")[0].start.knownValues
Uncaught TypeError: Cannot read property 'start' of undefined
```

...and it continues up to timezone offsets starting with 24:

```
> chrono.parse("2200-24")[0].start.knownValues
Uncaught TypeError: Cannot read property 'start' of undefined
```

But from 25 and above, the behaviour seems weird:

```
> chrono.parse("2200-25")[0].start.knownValues
{ hour: 22, minute: 0, meridiem: 1, timezoneOffset: -1500 }
```

I don't yet know what the expected behaviour should be for these cases.  They look a bit like time/timezone-offset strings, but they also look a bit like mathematical expressions.

**Comment by wanasit** [comment]
addressed that in https://github.com/wanasit/chrono/commit/4756d0dd5b816d3e5aa3b90024e064750ce82f98.
