### ISSUE TITLE
Time not working when used with in

### ISSUE THREAD

**Issue by typhoon11** [wanasit/chrono#423]
When I am using the sentence `wash clothes in 5mins` or `wash clothes in 5 minutes` it's returning wrong time but when I am using `wash clothes after 5mins` it's working, don't know what's wrong with `in` it's returning wrong time

**Comment by wanasit** [comment]
Hello. Sorry for my slow reply. I'm afraid I cannot really reproduce it with only that level of info. Could you be more precise about the actual output including reference time, and [what you expect] vs [the actual output]?

It would be nice if you could verify [if we already have that in the "in" test cases](https://github.com/wanasit/chrono/blob/master/test/en/en_time_units_within.test.ts).

**Comment by typhoon11** [comment]
So for example I send a sentence, `Wash dish in 1 hour`, the format it's sending is
![image](https://user-images.githubusercontent.com/66431066/152367860-1517d2d4-361e-4aee-8b7a-01f3648123aa.png)
Whose timestamp is - 1643900155
The timestamp when a ran the command - 1643900321

The time it's returning is of past when using `in`

**Comment by wanasit** [comment]
Sorry for my very slow reply.

I think misunderstand the `refDate` as the result.

You suppose to use `ParsingResult.date()` or `ParsingResult.start.date()`, not the reference (see: [the document](https://github.com/wanasit/chrono#parsedresult)). Or, call parseDate() not parse().
```
chrono.parseDate("Wash dish in 1hour")
> ...

chrono.parse("Wash dish in 1hour")[0].date()
> ...
```
