### ISSUE TITLE
Default to upcoming day of the week

### ISSUE THREAD

**Issue by j6k4m8** [wanasit/chrono#43]
There is perhaps a good reason for this behavior, so forgive me if this is intentional! My thought is that something like `Friday` should 'assume' `[this] Friday`, in that I am more likely to refer to an upcoming date than a past date by the day-of-the-week alone. (I think one would be more likely to refer to a past Friday as `last Friday`, even if it was only two or three days ago.) 

I'm looking through the code now to see if I can PR; let me know if I should abandon!

**Comment by wanasit** [comment]
It really depends on the application and the type of text that you parse (Appointments, News, Emails, etc). 

So, I don't think it good idea to assume that everything is upcoming date. Instead, I currently compare the closest 7-days window (from the reference date) to calculate default weekday, which I **personally** think quite reasonable for most domain. 

However, I'm not going to stop you if you want to customize it. I would be happy to see your pull-request.
