### ISSUE TITLE
What is necessary for full support?

### ISSUE THREAD

**Issue by georgd** [wanasit/chrono#436]
`de` is marked as partially supported. What are the required parts for full support?

**Comment by wanasit** [comment]
There is no clear boundary between "full" and "partial", but I think the most important difference is recognizing **data/time reference** in addition to the normal date/time.

for example, in English, you could do:
```
// Normal date/time
chrono.en.parseDate("2022-02-22") // OK
chrono.en.parseDate("Tueday 2pm") // OK

// Reference 
chrono.en.parseDate("in 2 hour 4 minute") // OK
chrono.en.parseDate("three days ago") // OK
```

In DE:
```
chrono.de.parseDate("12. Juli um 19 Uhr") // OK
chrono.de.parseDate("an 2 tag") // Not, support
```

**Comment by georgd** [comment]
Thank you. I think, I have identified what is missing, by comparing with the English and French localisations. My JS knowledge is not the best but the English and French localisations contain everything which I need to complete the DE localisation (once the test issue is fixed, which currently blocks my contributions).
