### ISSUE TITLE
Question: financial support

### ISSUE THREAD

**Issue by xxczaki** [wanasit/chrono#443]
Hi, thank you so much for developing and maintaining this library. Right now this is likely the best one we have in the JavaScript/TypeScript ecosystem when it comes to natural language date parsing. I'm using it in my product - [Parsify Desktop](https://parsify.app), which is a notepad-based calculator :smile:

My question is: are you accepting financial support right now? And if not, are you planning on opening a [GitHub Sponsors](https://github.com/sponsors) account, or maybe an [Open Collective](https://opencollective.com/) page? 

I (and possibly others) would be really happy to contribute a small monthly donation to support further development!

**Comment by wanasit** [comment]
Thank you for asking, but I don't need financial support.
(I'm working joining the GitHub Sponsors program though)

I am appreciate your recognition of my work, but I think a better way to use that money would be paying a bonus (or buying coffee/beer) for other engineers in your company to study and contribute to the project :)
