### ISSUE TITLE
Moment specified as dependency for NPM but not Bower?

### ISSUE THREAD

**Issue by ianwalter** [wanasit/chrono#45]
How come? I'm trying to build src with webpack, but it's complaining about momentjs not being there. I suppose I could install via NPM, but I'm using it in the browser not Node.

**Comment by wanasit** [comment]
Hi Ian. I've not used webpack before, but just try in minutes ago and it works without any error.

I ran webpack command on the project top folder like this:
```
webpack src/chrono.js out.js
```
