### ISSUE TITLE
Parsing of UTC time offset

### ISSUE THREAD

**Issue by magin** [wanasit/chrono#46]
There seems to be a problem with parsing the offset from UTC:
 
try parsing these dates: `Sat, 21 Feb 2015 11:50:48 -0500`, `22 Feb 2015 04:12:00 -0000`

Chrono parses it as `Sat Feb 21 2015 11:50:48 GMT-0800 (PST)` should be parsed in EST time

if you try `Sat, 21 Feb 2015 11:50:48 -0500 EST` it works as expected.

**Comment by wanasit** [comment]
Thank you for sharing. Fixed in 4450b18.
