### ISSUE TITLE
inconsistent behaviour

### ISSUE THREAD

**Issue by Mtillmann** [wanasit/chrono#464]
```javascript
    let schedules = [
            ['next_morning', chrono.parse('Tomorrow at 10:00', new Date('08-02-2022'))[0].start.date()],
            ['next_evening', chrono.parse('Tomorrow at 19:00', new Date('08-02-2022'))[0].start.date()],
            ['next_saturday', chrono.parse('next Saturday at 11:00', new Date('08-02-2022'))[0].start.date()],
            ['next_sunday', chrono.parse('next Sunday at 15:00', new Date('08-02-2022'))[0].start.date()]
        ];
```
yields 
```javascript
[
 [ 'next_morning', 2022-08-03T08:00:00.000Z ],
 [ 'next_evening', 2022-08-03T17:00:00.000Z ],
 [ 'next_saturday', 2022-08-13T09:00:00.000Z ],
 [ 'next_sunday', 2022-08-07T13:00:00.000Z ]
]
```

`next_sunday` works as expected while `next_saturday` is one week off. Am I missing something?

**Comment by Mtillmann** [comment]
FWIW, the following `chrono.parse`-syntax seems to yield the desired values:

```javascript
 let referenceDate = new Date('08-02-2022'),
      parsingOptions = {
          forwardDate: true
      },
      schedules = [
          ['next_morning', chrono.parse('Tomorrow, 10:00', referenceDate, parsingOptions)[0].start.date()],
          ['next_evening', chrono.parse('Tomorrow, 19:00', referenceDate, parsingOptions)[0].start.date()],
          ['next_saturday', chrono.parse('Saturday, 10:00', referenceDate, parsingOptions)[0].start.date()],
          ['next_sunday', chrono.parse('Sunday, 15:00', referenceDate, parsingOptions)[0].start.date()]
      ];
```

**Comment by wanasit** [comment]
Hello. Thanks for reporting.

What happened was the reference date "August 2, 2022 - Tuesday" (enum date 2)
* The "next Sunday" (enum date 0) is 5 day later
* But, the "next Saturday" is (date enum  6) is 4+7 day later

Calculating "next" based on the date-enum-offset rather than date-window seems like a bug.

However, deciding e.g. what is "Saturday" vs "Next Saturday" has been a difficult edge case, I need some more time to check if it doesn't break any current tests.

**Comment by wanasit** [comment]
The d0551cd350f00fce11fa7e9fa860e9d93679047d fixes this issue, but there are other changes relating to the day of the week I want to clean up.

It should be released in the new minor version (2.4.0) sometime next week.

**Comment by Mtillmann** [comment]
@wanasit Thanks a lot for taking the time mate 🙇

**Comment by wanasit** [comment]
Publish please update to `2.4.1+`
