### ISSUE TITLE
ISO8601 time zone is parsed wrong

### ISSUE THREAD

**Issue by niobos** [wanasit/chrono#47]
Hi,

There seems to be a time zone bug in parsing ISO timestamps:
`2015-03-23T12:00:00+00:00` is correctly parsed to 1427112000000 ms since epoch (Mon Mar 23 2015 13:00:00 GMT+0100 (CET)).
`2015-03-30T12:00:00+00:00` however, is incorrectly parsed to 1427713200000 ms since epoch (Mon Mar 30 2015 13:00:00 GMT+0200 (CEST)), i.e. one hour earlier than the text indicates.

I guess that the issue has something to do that, by March 30th, my timezone will have shifted from GMT+1 to GMT+2, even though the timestamps indicate the timezone to be used.

Additional data points: if I change the timezone on the timestamp after March 29th, they all seem to be 1 hour wrong. Other dates during DST also seem to have the 1 hour offset.

**Comment by wanasit** [comment]
@niobos I can't reproduce the bug you mention. My `chrono.parseDate('2015-03-30T12:00:00+00:00').getTime()` returns 1427716800000. 

Maybe it can happen only JS configured to sometime zone.
Could you please try running chrono's unittest on your machine?
(`npm install` then `npm test`)

**Comment by wanasit** [comment]
Ok. I think I got an idea what happened.

Chrono adjust the timezone offset by comparing the parsed timezone offset with a new Date object's timezone offset (your timezone offset as you running the code), which may not be the correct timezone offset at that time.

See `src/result.js` lines ~90
```Javascript

var currentTimezoneOffset = -new Date().getTimezoneOffset();
...
var adjustTimezoneOffset = targetTimezoneOffset - currentTimezoneOffset;
dateMoment.add(-adjustTimezoneOffset, 'minutes');
return dateMoment.toDate();
```

So, I guess the result gonna be correct again if you run it after 29 March :P.
Or until I can think of a clean way to fix it.

**Comment by niobos** [comment]
> So, I guess the result gonna be correct again if you run it after 29 March :P.

Yes, but then the dates from non-DST part of the year will be wrong...

**Comment by wanasit** [comment]
Yeah... you know it ^^
So, please give me sometime to fix it.

**Comment by niobos** [comment]
I'll try to come up with a patch myself as well. I'm trying to understand the code at the moment

**Comment by niobos** [comment]
What about?
```diff
--- chrono.js.old       2015-03-24 14:01:42.821274324 +0100
+++ chrono.js   2015-03-24 14:01:52.265245789 +0100
@@ -4721,7 +4721,7 @@
     dateMoment.set('millisecond', this.get('millisecond'));
 
     // Javascript Date Object return minus timezone offset
-    var currentTimezoneOffset = -new Date().getTimezoneOffset();
+    var currentTimezoneOffset = -dateMoment.zone();
     var targetTimezoneOffset = this.isCertain('timezoneOffset') ? 
         this.get('timezoneOffset') : currentTimezoneOffset;
```

This seems to work in my few test cases...

**Comment by wanasit** [comment]
That's look nice!
The doc says `zone()` will be deprecated, maybe we should consider using `utcOffset` or lock moment's version.

**Comment by wanasit** [comment]
If it works, could you please create a pull request.
Thanks~!

**Comment by niobos** [comment]
`utcOffset()` is only supported in moment.js 2.9.0 and up. The current bundled version is 2.8.4.
