### ISSUE TITLE
Round to beginning of date

### ISSUE THREAD

**Issue by dberardo-com** [wanasit/chrono#481]
how to round the return date to the closest "step", as in:
1, If now is 17:48:23 i would like to return 17:00 (step hour)
2. If now is 17:48:23 i would like to return 17:48:00 (step minute)
3. If now is 17:48:23 i would like to return 17:00:00 (step 24hours)
4. .... etc.

i have tried with "beginning of current hour" or even "one hour ago o'clock". but none seems to work .. any hint ?

**Comment by wanasit** [comment]
If chrono's results for parse() functions are `ParsingResult` and `ParsingComponents` (see `src/results.ts`). On the ParsingComponents, you could simply assign 0 to truncate the hour or minute.

```
let result = chrono.parse('Now')[0];
result.start.date() 
// Sun Dec 04 2022 11:41:59 GMT+0900 (Japan Standard Time)

result.start.assign('minute', 0);
result.start.assign('second', 0);
result.start.assign('millisecond', 0);
result.start.date() 
// Sun Dec 04 2022 11:00:00 GMT+0900 (Japan Standard Time)
```

**Comment by dberardo** [comment]
Well that would work of course, but needless to say, o would like the library to guess that for me.

So if the user wants it rounded by hour or by day, this will be handled in the same way. So my question was whether the library can achieve this smart behavior as well
