### ISSUE TITLE
Shorthand relative time format

### ISSUE THREAD

**Issue by asportnoy** [wanasit/chrono#487]
Chrono should be able to support shorthand (abbreviations) for relative time. Some of them work already, but some are missing:

- ❌ 1s ago
- ❌ 1m ago
- ✅ 1h ago
- ❌ 1d ago
- ❌ 1w ago
- ❌ 1mo ago
- ✅ 1y ago

Same applies for future time ("in ___")

**Comment by wanasit** [comment]
Supported this in 8abbd83.
