### ISSUE TITLE
Forced american formatting

### ISSUE THREAD

**Issue by kieran-s** [wanasit/chrono#492]
Whenever I enter a date string (eg. 04/03/2022), it automatically defaults to the American formatting for parsing (mm/dd/yyyy).

How do I force it to use my regions formatting (dd/mm/yyyy) for when someone enters a date

**Comment by wanasit** [comment]
There are `chrono.en.GB` built-in variant:
```
chrono.parseDate('6/10/2018');            // June 10th, 2018
chrono.en.parseDate('6/10/2018');       // June 10th, 2018
chrono.en.GB.parseDate('6/10/2018');    // October 6th, 2018
```

If the built-in type doesn't work, you can follow the guide on [Customizing Chrono](https://github.com/wanasit/chrono#customize-chrono).
```typescript
import SlashDateFormatParser from "../src/common/parsers/SlashDateFormatParser";

const custom = chrono.en.strict.clone();
// Replace any existing SlashDateFormatParser with the little-endian one.
custom.parsers = custom.parsers.filter((r) => !(r instanceof SlashDateFormatParser));
custom.parsers.push(new SlashDateFormatParser(/*littleEndian=*/true));
```
