### ISSUE TITLE
Error: undefined is not an object (evaluating 'chrono.parse')

### ISSUE THREAD

**Issue by penne12** [wanasit/chrono#50]
`Error: undefined is not an object (evaluating 'chrono.parse')` when I run `var date = chrono.parse(homework.input)[0]`
I'm using bower and including `/bower_components/chrono/chrono.min.js`.

**Comment by tanc** [comment]
I have the same question. How do I use this library on a client side application?

**Comment by penne12** [comment]
I got this working in a very weird way with some client side wrapping here: penne12/PlanHW-Front-End

**Comment by wanasit** [comment]
Hi. Sorry for my slow response. I just tried install with bower in my computer and it worked fine. 
Hope you have already got it to work too.
