### ISSUE TITLE
forwardDate doesn't work when there is a range of dates

### ISSUE THREAD

**Issue by neoromantic** [wanasit/chrono#505]
Specifically, I have this example:

```
chrono.ru.parse("С мая по ноябрь", new Date(), {forwardDate: true})
```
, which returns November of 2022 and May of 2023 instead of all dates be in 2023, as it should.

Same happens in English:
```
chrono.parse("From May to November", new Date(), {forwardDate: true})
```

**Comment by wanasit** [comment]
Thanks for reporting this.
Fixed in 665bda6b7c308166e08dbf4acf7d8ce926e38be9.
