### ISSUE TITLE
sideEffects should be a boolean or an array

### ISSUE THREAD

**Issue by danielepolencic** [wanasit/chrono#506]
When bundling chrono-node, I can observe the following warnings:

```
▲ [WARNING] The value for "sideEffects" must be a boolean or an array [package.json]

    ../../../../../../../../execroot/my-project/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/chrono-node@2.6.1/node_modules/chrono-node/dist/cjs/package.json:1:33:
      1 │ {"type":"commonjs","sideEffects":"false"}
        ╵                                  ^
```

I think this was introduced in the latest release.

**Comment by JoakimNil** [comment]
This property should definitely be a boolean ([webpack docs](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free)). I can submit a PR to fix this over the weekend @wanasit unless you want to handle it?

**Comment by wanasit** [comment]
I'm not good at JS build and I haven't looked into this. If you already know what to do, I'd be glad if you could help :)
