### ISSUE TITLE
Wrong start date when string has something before the start date

### ISSUE THREAD

**Issue by Pranoy1c** [wanasit/chrono#512]
The following gives the wrong start date. It gives start date as 03 instead of 17.

```
let parsed = chrono.parse('Appointments from 17 August 2013 to 19 August 2013')[0]

console.log(parsed.start.date()) // prints: Sat Aug 03 2013 12:00:00 GMT-0400 (Eastern Daylight Time)
console.log(parsed.end.date()) // prints: Mon Aug 19 2013 12:00:00 GMT-0400 (Eastern Daylight Time)
```

Even if the string is `' 17 August 2013 to 19 August 2013'`
it gives the wrong result for start date. NOTE the space before 17

**Comment by wanasit** [comment]
Thanks for reporting this. This should be fixed in 0640c1ea17c6dbb6a814b55f46a1e55e6497ae8a.
