### ISSUE TITLE
Better contribution guide

### ISSUE THREAD

**Issue by penne12** [wanasit/chrono#52]
Could you add one so hopefully contributors (maybe me) can understand the project more?

**Comment by wanasit** [comment]
Hi. I apologize for not having good contribution guide (and also super slow response). I'll work on this as soon as I have time.

**Comment by penne12** [comment]
Don't worry about it! Id love to help when I know how :smile:

**Comment by wanasit** [comment]
Just wrote development guild part in the readme file. This should be helpful if for you and other people to setting up the development env for Chrono. 
https://github.com/wanasit/chrono#development-guild

Will write more when I have time.

**Comment by penne12** [comment]
Thanks!

**Comment by penne12** [comment]
@wanasit, you might have typed 'guild' instead of guide.
