### ISSUE TITLE
Expose ReferenceWithTimezone and ParsingComponents classes

### ISSUE THREAD

**Issue by gcampax** [wanasit/chrono#526]
Hello!
We have a use case where we are using chrono to parse dates of the format "$date for $duration" (eg. "8/10/2023 8am for 30 minutes". We use `parse-duration` to parse the duration part.
In chrono 2.3.1, we then used a refiner to attach the duration as the end instant of the date with ParsingComponents.createRelativeFromRefInstant, using an internal import to get to the ParsingComponents class. The internal import no longer works in recent chrono though, due to the filtering done by package.json exports.
Would it be possible to expose ParsingComponents as part of the public API, as well as the ReferenceWithTimezone class which used by createRelativeFromReference (successor of createRelativeFromRefInstant)?
Thanks!

**Comment by wanasit** [comment]
Hello @gcampax. I'm sorry for not getting back to you sooner. 

I have always intended to include `ParsingComponents` and `ReferenceWithTimezone` in the public interface (e.g. `ParsingResult` is already added). Sorry, I didn't notice we have removed them at some point. 

---

Added them back in 99b2e9f8af17cb39be1777fc7e8a1335b0d257b6.

**Comment by gcampax** [comment]
That is great, thank you so much for fixing this so quickly, and thanks for the great library! :)
