### ISSUE TITLE
'x months ago' and 'x years ago' queries do not work

### ISSUE THREAD

**Issue by dmonopoly** [wanasit/chrono#53]
These would be nice additions. Currently they return null.

**Comment by dmonopoly** [comment]
I suppose these could be solved using Sugar.js's similar methods... http://sugarjs.com/features#date

**Comment by thomasfoster96** [comment]
:+1: These would be great to have.

**Comment by xpepermint** [comment]
+1

**Comment by wanasit** [comment]
I've added 'x months ago' and 'x years ago' in the latest version. (Not allowed in `strict` mode)

```javascript
chrono.parseDate('5 months ago')
// Wed Jun 03 2015 12:00:00 GMT+0900 (JST)

chrono.strict.parseDate('5 months ago')
// null
```

**Comment by xpepermint** [comment]
@wanasit thx
