### ISSUE TITLE
Invalid parsing: `08/08/2023, 09:15 AM to 08/29/2023, 09:15 AM`

### ISSUE THREAD

**Issue by baptisteArno** [wanasit/chrono#533]
Whenever I try to parse a range formatted like this: `08/08/2023, 09:15 AM to 08/29/2023, 09:15 AM`

It fails to read the 2nd date because it first matches `08/08/2023, 09:15 AM to 08`

**Comment by jadigar** [comment]
Similar issue: https://github.com/wanasit/chrono/issues/531

**Comment by wanasit** [comment]
Should be fixed with https://github.com/wanasit/chrono/commit/9651e1d55f9d9f2722c7d870f1200cff1f912abb (tested in https://github.com/wanasit/chrono/commit/6ae88ecb79185081cb907ee5f2c73b35ee268b7c)
