### ISSUE TITLE
July 42nd = August 11th, etc

### ISSUE THREAD

**Issue by schnauss** [wanasit/chrono#54]
To replicate:
```alert(chrono.parseDate("July 42nd"));```

This should respond with some kind of error. Instead, it returns an actual date, albeit one not in July.

**Comment by BtM909** [comment]
Why would it return with an error? It is actually correct since August 11th is the 42nd day from July (1st).

I would consider chrono a parser and not a validator. Shouldn't it only return an error when there's an error while trying to parse the given text?

**Comment by wanasit** [comment]
In the latest version, you can disallow those impossible dates by `strict` mode.

```
chrono.parseDate("July 42nd")
> Tue Aug 11 2015 12:00:00 GMT+0900 (JST)
chrono.casual.parseDate("July 42nd")
> Tue Aug 11 2015 12:00:00 GMT+0900 (JST)

chrono.strict.parseDate("July 42nd")
> null
```
