### ISSUE TITLE
de locale in parse function

### ISSUE THREAD

**Issue by q16marvin** [wanasit/chrono#545]
Hi, 

i try something like this:

`const chronoedAll = chrono.de.parse(
    cmd,
    {
      instant: new Date(),
      timezone: -getUTCOffset(new Date(), findTimeZone(timezone)).offset,
    },
    {
      forwardDate: true,
    }
  );
  if (chronoedAll[1]) console.log(`Found multiple dates in ${cmd}`, chronoedAll);`

but than i to got this:

> src/command.ts(49,7): error TS2345: Argument of type '{ instant: Date; timezone: number; }' is not assignable to parameter of type 'Date'.  Object literal may only specify known properties, and 'instant' does not exist in type 'Date'.

without locale it is working, but i want to test it with "de". what i do wrong?

**Comment by q16marvin** [comment]
forget it, im stupid

**Comment by wanasit** [comment]
Hello. Thanks for letting me know.

Those locale-specific shortcut functions' Typescript interface are outdated. I updated them in `fa472f2049fd3ffc4ae6d9a479203ff6e0501156`. After the update, you should be able to call `chrono.de.parse(..., {instant: ...})` as in `chrono.parse()`.
