### ISSUE TITLE
Error parsing of local time in the Common Log Format (06/Nov/2023:06:36:02 +0200)

### ISSUE THREAD

**Issue by JoobyPM** [wanasit/chrono#547]
This format used in nginx access logs ($time_local). Local time in the Common Log Format;

Example:
```js
//..
chrono.parseDate("06/Nov/2023:06:36:02 +0200")
// output: Mon Nov 06 2023 12:00:00 GMT+0000 (Western European Standard Time)
```

**Comment by wanasit** [comment]
Hello. Thanks for reporting this. 

I have fixed this in 3ae3144. Please wait for the next release (2.7.6+).
