### ISSUE TITLE
Incorrect parsing of Chinese for 'tomorrow morning at 8am'

### ISSUE THREAD

**Issue by pjrobertson** [wanasit/chrono#548]
tomorrow morning at 8am in Chinese is: `明天早上 8 点` 
([ref](https://translate.google.com/?sl=auto&tl=zh-CN&text=tomorrow%20morning%20at%208am&op=translate))

This returns the wrong time (always returns 6am in the morning, no matter what the hour is). 

To reproduce:

```node
// node
const chrono = require('chrono-node');
console.log(chrono['zh'].parseDate("明天早上8点"))
```

**Comment by wanasit** [comment]
The default configuration has been mapped to traditional Chinese (`chrono.zh.hant`). If you switch to simplified Chinese `chrono.zh.hans`, it should work (e.g. chrono.zh.hans.parseDate("明天早上8点")).

I'm also updating the default `chrono.zh` to handle both traditional and simplified Chinese at the same time in c5261b7.

**Comment by pjrobertson** [comment]
Amazing! Thanks 👍🏼
