### ISSUE TITLE
v1.x isCertain returns unexpected values

### ISSUE THREAD

**Issue by surrealroad** [wanasit/chrono#555]
This might just be me misunderstanding what's supposed to happen, but (in the v1 branch):
```
results = chrono.parse('tomorrow');
results[0].start.isCertain('year') // true
results[0].start.isCertain('month') // true
results[0].start.isCertain('day') // true
results[0].start.isCertain('hour') // false
results[0].start.isCertain('minute') // false
results[0].start.isCertain('second') // false
```

This works as expected. However:
```
results = chrono.parse('in 5 minutes');
results[0].start.isCertain('year') // false
results[0].start.isCertain('month') // false
results[0].start.isCertain('day') // false
results[0].start.isCertain('hour') // false
results[0].start.isCertain('minute') // false
results[0].start.isCertain('second') // false
```

Here I would expect hour/minute/second to be `true` and the others `false`. 

For now I've written my code to look specifically for `isCertain('year') && isCertain('month') && isCertain('day') && !isCertain('hour') && !isCertain('minute') && !isCertain('second')` to try to answer the question "can I ignore the time component from this query?", which seems to work.

**Comment by wanasit** [comment]
I fixed this in b12f412 and published v1.4.9.

However, I noticed there are probably more issues that have already been fixed in v2 and I have less time to keep them both up-to-date. For the longer term, you should update to v2.
