### ISSUE TITLE
Wrong result for a simple case

### ISSUE THREAD

**Issue by masylum** [wanasit/chrono#556]
Hello!

I just wanted to bring up a case that I think should be fairly straightforward to fix.

`8:23 AM ∙ Jul 9` currently wrongly converts to `2022 2024-06-13T08:23:00.000Z`

I can help if need be, but I don't know where to even start :)

**Comment by wanasit** [comment]
Thanks for reporting this. I fixed this in 23abdda.

**Comment by masylum** [comment]
Awesome!
