### ISSUE TITLE
Ambiguity in parsing numerical dates

### ISSUE THREAD

**Issue by sharon-office** [wanasit/chrono#562]
`let date1 = '1/13/2024'
let result1 = chrono.parseDate(date1);
console.log(result1.toDateString());  // Jan 13 2024

let date4 = '2024/13/1'
let result4 = chrono.parseDate(date4);
console.log(result4.toDateString());  // Jan 13 2025  ISSUE`

second result is a wrong answer, it has to give 2024 Jan 13,
or else if chrono cannot parse this , it should have return null right?

Is my observation correct or is there any extra logic on that?

**Comment by wanasit** [comment]
Thanks for reporting.

I fixed this in d61f933.
