### ISSUE TITLE
Adding new language: ko

### ISSUE THREAD

**Issue by Jeong-minji** [wanasit/chrono#563]
#529 

I referenced the above issue, and I want to contribute new language `ko (Korean)`.
I will make small incremental CRs after making new codes. 

I have few questions,
- Do I just need to specify @wanasit as a reviewer?
- Is there a convention for the test case or should I write them autonomously?

**Comment by wanasit** [comment]
Hello. Thanks for reaching out.

> Do I just need to specify @wanasit as a reviewer?
Yes. Or just create a Merge Request; I'll look at the change.

> Is there a convention for the test case or should I write them autonomously?

There is a strict convention, but please follow the existing tests.
Note that I (and other contributors) don't speak Korean, the tests should be easy to understand.

Anyway, don't worry too much. 
If it's not too large change, I'll check and approve it as soon as I can.
