### ISSUE TITLE
bug: due to 1.4.9 backport the incorrect version is marked as latest on GitHub and NPM

### ISSUE THREAD

**Issue by favna** [wanasit/chrono#566]
Due to backporting features to 1.4.9 running `npm install chrono-node` will currently install v1.4.9 because it's marked as `latest` on npm: https://www.npmjs.com/package/chrono-node

![image](https://github.com/user-attachments/assets/fe51d0b2-9a7a-4b6b-ac1a-e63d76c14b87)

The fix is to run `npm dist-tag` to move the latest tag, see https://docs.npmjs.com/cli/v8/commands/npm-dist-tag/

As for GitHub, the 1.4.9 release should be edited removing the "mark as latest" checkbox and then do the same in reverse for latest v2.

**Comment by wanasit** [comment]
Ops. Sorry for the problem.

When releasing 1.4.9, I originally planned to release 2.7.7 on the same day. However, I didn't complete the later. 

This should be fixed after 2.7.7 this week.
