### ISSUE TITLE
Parse [MM.DD] pattern as a date

### ISSUE THREAD

**Issue by lemorage** [wanasit/chrono#570]
Now, I know the `MM-DD` and `MM/DD` will be parsed as a date, but is it possible to parse `MM.DD` pattern as a date as well?

**Comment by wanasit** [comment]
Similar to the bug reported in https://github.com/wanasit/chrono/issues/571. 

Writing "MM-DD" and "MM.DD" as a date is less common in English (e.g. "11.12" would seem like a version number, not a date).

For your use case, if you confidence that those are date, I would recommend create a custom Chrono instance without `EnTimeExpressionParser` and `UnlikelyFormatFilter`.
