### ISSUE TITLE
Property `isOnlyTime()` does not exist on type 'ParsedComponents'

### ISSUE THREAD

**Issue by bytrangle** [wanasit/chrono#573]
For the ParsedComponents, I'm able to call `isCertain()`, but not `isOnlyTime()`. The only methods available according to Intellisense are `get()`,  `date()`, `get()`, and `tags()`. I'm using the latest version, 2.7.7.

**Comment by wanasit** [comment]
The `isOnlyTime()` (and `isOnlyDate()`) belong to `ParsingComponents` (not `ParsedComponents`), an internal API for writing parsers and refiners. It should be used with caution (e.g. calling isOnlyTime() on a relative date like "1 day ago" may not be correct).

I'm hesitating to expose those methods to the more visible `ParsedComponents` type.
Could you explain your use case and the need for the methods to be included in the result type?

**Comment by bytrangle** [comment]
Thanks for getting back. The to-do app Super Productivity allows users to add start date for their to-dos using natural language, backed by `chrono` :).
If a user only enters time with no date, how should you interpret it?
For example: "Laundry 4pm".
The start date for this task will depend on **when** the user creates the task:
- current time is 3pm => start date is today
- current time is 5pm => start date is 4pm of the next day because there is little use for a start time in the past.

Hope that makes sense, although I've started to see how using `isOnlyTime()` carelessly will open a can of bugs!

**Comment by wanasit** [comment]
Thanks for explaining your use case. 

However, I still think exposing `isOnlyTime()` on `ParsingComponents` public interface is too risky for future maintenance and other use cases. 

I suggested implementing a similar check on your side. Note that [the actual isOnlyTime is also just one line](https://github.com/wanasit/chrono/blob/master/src/results.ts#L134-L138). You can just copy it to your project if you need to, but as discussed, you should add extra checking for your use case as well.
