### ISSUE TITLE
Doesn't appear to parse ISO local times

### ISSUE THREAD

**Issue by ndarilek** [wanasit/chrono#60]
chrono.parseDate("2015-07-31T12:00:00")
    Date {Wed Jul 15 2015 20:15:00 GMT-0500 (Central Standard Time)} (Date)

If I give it 2016-07-31..., the time is displayed as 20:16:00.

It'd be great if this ISO format was supported, since I'm using a library that expects it. Thanks!

**Comment by wanasit** [comment]
It should be able to handle ISO string. This is a bug.

Found that it's need 'z' to work. Will fix this soon.
```
chrono.parseDate("2015-07-31T12:00:00z")
> Fri Jul 31 2015 21:00:00 GMT+0900 (JST)
```
