### ISSUE TITLE
"tomorrow" yields incorrect date

### ISSUE THREAD

**Issue by bendavis78** [wanasit/chrono#62]
`chrono.parseDate("tomorrow", new Date(2015, 0, 1))` should give "2015-01-02".

**Comment by wanasit** [comment]
I don't think that's a bug. If you says "tomorrow" during the night (12.00 AM - 4 AM), it's normally mean the morning. Try `chrono.parseDate("tomorrow", new Date(2015, 0, 1, 6))`

**Comment by bendavis78** [comment]
Ok, that makes sense. However, 4am seems like a rather arbitrary number. Perhaps this should be configurable? Some people might define the "day start" time differently than others.
