### ISSUE TITLE
Submit to JSDelivr

### ISSUE THREAD

**Issue by bradvogel** [wanasit/chrono#66]
Would be great to have this on JSDelivr so we can download it with our other scripts (via JSDelivr's concatenation feature).

See https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

**Comment by bradvogel** [comment]
ping :)

**Comment by wanasit** [comment]
Thanks for letting me know. And sorry for my super slow response.

Just submit the PR: https://github.com/jsdelivr/jsdelivr/pull/8319
