### ISSUE TITLE
now?

### ISSUE THREAD

**Issue by griojas** [wanasit/chrono#70]
Trying the parser, i wanted to get Now(), specially important for my project, but it seems not to be supported.
Is there any suggestion or workaround for this?

**Comment by penne12** [comment]
Try creating your own ["parser"][0].

[0]: https://github.com/wanasit/chrono#parser

**Comment by wanasit** [comment]
Do you mean detecting string - "now" as a date? Something like: `if (test.indexOf("now") >= 0) return new Date();`?

**Comment by penne12** [comment]
@wanasit Yeah
