### ISSUE TITLE
Export parsers / refiners

### ISSUE THREAD

**Issue by bradvogel** [wanasit/chrono#71]
It'd be nice to export the internal parsers / refiners so we cherry pick which ones we want to add. For example, if I want all of them except for 'UnlikelyFormatFilter', I need to do:

```
  var obj = new chrono.Chrono(chrono.options.casualOption());

  obj.refiners = _.reject(obj.refiners, function(refiner) {
    return refiner.constructor.name == 'UnlikelyFormatFilter';
  });
```

Instead I'd like to add them directly, e.g.

```
new chrono.Chrono(function(){
   return {
      parsers: [
          chrono.builtIn.ENISOFormatParser(true /* Strict */)
      ],
      ...
   };
});
```

**Comment by penne12** [comment]
+1

**Comment by wanasit** [comment]
Agree. From version 1.1.0, chrono will export those parsers and refiners through `chrono.parser` and `chrono.refiner` objects.

If you want to cherry pick those parsers/refiners, you can do so. (It will slightly different from what you suggested)
```
new chrono.Chrono({
      parsers: [
          new chrono.parser.ENISOFormatParser(true /* Strict */)
      ],
      ...
});
```

See the change here: https://github.com/wanasit/chrono/commit/9a7801cb63f0033dabd46b98f0776b2ed08b5f58
