### ISSUE TITLE
Incorrect parse results

### ISSUE THREAD

**Issue by nathanpeck** [wanasit/chrono#72]
This string causes bad parse results:

```
1.5.3 - 2015-09-24
```

Results:

```
Sun Nov 29 2015 01:05:03 GMT-0500 (EST)
```

The original string is a version number, and an ISO date.

It is interpreting the version number as the hour, minute, and second, which is fine. I only care about the day anyway. However, for some reason it also interprets the date as being the 29th, instead of the 24th, which isn't acceptable.

Removing the dash "fixes" the problem.

**Comment by wanasit** [comment]
Fixed.

https://github.com/wanasit/chrono/commit/6e0653aab8d46c2ecbb12ea44c4f8dcc60def1ff

**Comment by nathanpeck** [comment]
Awesome! Thanks!
