### ISSUE TITLE
prefix ?

### ISSUE THREAD

**Issue by penne12** [wanasit/chrono#73]
Can you add support for only picking a date if it has a prefix in front (`due [date]`, `by [date]`, `on [date]`), or at least matching a prefix if it exists? This would be super useful for calendar and reminder apps.

**Comment by wanasit** [comment]
You can check the prefix and build the calendar or reminder extraction by taking advantage of `index` field returned in the result.

```javascript
var text = 'XXXX by next tuesday';
var dateResults = chrono.parse(text);
// if (dateResults.length == 0) ...

var prefix  = text.substr(0, chrono.parse(text)[0].index);
var prefixMatch = prefix.match(/(by|due)\s$/))
if (prefix.match(/(by|due|on)\s$/)) {
  // extract XXX
}
```

That said, I don't think that feature should be built inside Chrono.

**Comment by penne12** [comment]
Ok! Thanks! I got this to work. The main reason I was asking was if someone typed "Read about 9/11 due next Friday". Or something.
