### ISSUE TITLE
"Next next [any day of week]" doesn't work when the dates are divided by new year

### ISSUE THREAD

**Issue by balasphilip** [wanasit/chrono#77]
go to https://wanasit.github.io/pages/chrono/ and inside the textarea try to type: "next next [any day of week]" - then the date will move just to the next week (e.g.: from 12/22/2015 after typing "next next Monday" date will changed to 28/12/2015 ).
Please see my example: http://prntscr.com/9h64vb

**Comment by penne12** [comment]
Great job on catching that corner case!

**Comment by wanasit** [comment]
Currently, parser takes only one "next" (Ex. "next [next Tuesday]"). And I don't think it should handle multiple "next"s either.

**Comment by balasphilip** [comment]
But it's working correctly with two "next" if the date is not divided by New Year. Just try to type "next next ..." now and see the result.

**Comment by penne12** [comment]
+1
