### ISSUE TITLE
Re-submit to JSDelivr, please

### ISSUE THREAD

**Issue by bradvogel** [wanasit/chrono#78]
Following up on https://github.com/wanasit/chrono/issues/66 (and subsequent PR https://github.com/jsdelivr/jsdelivr/pull/8319), it looks like the version submitted to JSDelivr isn't the full library. Compare https://cdn.jsdelivr.net/chrono/0.1.11/chrono.js to the expected version https://rawgit.com/wanasit/chrono/master/chrono.js

**Comment by wanasit** [comment]
Sorry for my slow response. I though the problem was simply the jsdelivr's bot delay and will be solved with the new version of Chrono.

I don't know what is the problem and I cannot solve it alone.
https://github.com/jsdelivr/jsdelivr/issues/8750

**Comment by wanasit** [comment]
Look like the issue on jsdelivr is closed https://github.com/jsdelivr/jsdelivr/issues/8750

Try: https://cdn.jsdelivr.net/chrono/1.1.0/chrono.js

**Comment by bradvogel** [comment]
Thanks!
