### ISSUE TITLE
Tomorrow is parsed as today before 1am

### ISSUE THREAD

**Issue by KrisSiegel** [wanasit/chrono#83]
I just started using chrono in a small app and I had some unit tests to verify some output that I generate based on the results of chrono. A few days ago I noticed "tomorrow" no longer returned the date for tomorrow but instead today.

I'm not sure of the cause yet but I do know it previously worked. Here is a jsfiddle demonstrating what I'm getting: https://jsfiddle.net/u5wrdj40/. At the time of this posting going by my local timezone it is Feb 8th. The results of parsing "tomorrow" are also returning Feb 8th.

If I'm somehow using this wrong please let me know but I had previously passing unit tests that at least led me to believe this was working before.

**Comment by penne12** [comment]
Couldn't reproduce (even in your fiddle)

**Comment by KrisSiegel** [comment]
Interesting! Rechecking the fiddle and node.js code this evening and it now produces the correct dates for "tomorrow" whereas it did not when I first submitted this ticket. I wonder if it's a timezone issue; perhaps it's not taking into account the local timezone correctly? I'll recheck it in a few hours and if I can reproduce it try to debug.

**Comment by penne12** [comment]
Hmm... checked your profile - and it lists city you live it. Looks like it was just past midnight for you, which might have caused a problem - I have a hunch on why - give me a second.

**Comment by penne12** [comment]
Yup - Chrono interprets tomorrow as today if you are using it from 12am-4am, presumably to avoid confusion from users who stay up late. 

https://github.com/wanasit/chrono/blob/master/src/parsers/EN/ENCasualDateParser.js#L40

**Comment by KrisSiegel** [comment]
Ah I had suspected that but hadn't gone into the code yet. At least that makes sense (especially considering that's typically when I work on this project, lol). I would much prefer to keep this constrained to 12:00 - 12:59:59 as that's when I typically consider others referring tomorrow as the same day so configurable would be handy (honestly I'd probably disable this completely).

Unless someone else is going to I'll probably fork and make configurable when I have some time later in the week. Thanks for looking into this; at least I know I'm not crazy!

**Comment by penne12** [comment]
@KrisSiegel 
Glad to help! I think that makes a lot more sense to only use 1 hour into the next day (thinking about that myself)

**Comment by wanasit** [comment]
@penne12 is right. The interpretation of words like "today", "yesterday", or "this morning" depends on the context.  

The second parameter of parse functions is `refDate`. By default, the `refDate = new Date()` (now).
```
chrono.parseDate("tomorrow", new Date(2015, 2-1, 13, 12, 00))
// "tomorrow at 12.00" > Sat Feb 14 2015 12:00:00 GMT+0900 (JST)
chrono.parseDate("tomorrow", new Date(2015, 2-1, 13, 0, 00))
// "tomorrow at 0.00" > Fri Feb 13 2015 12:00:00 GMT+0900 (JST)
```

I agree that  `12am-4am` is not really a nice choice. Will consider changing that too.

**Comment by penne12** [comment]
@KrisSiegel I've changed this to be only 1 hour past midnight - I'll work on making it configurable.

**Comment by KrisSiegel** [comment]
:+1: thanks!
