### ISSUE TITLE
Want to help supporting Spanish

### ISSUE THREAD

**Issue by gimenete** [wanasit/chrono#84]
Hi,

I would like to add parsers for spanish in this library. I've seen that probably everything for english parsers would be just a translation to spanish words. tomorrow = mañana, noon = mediodía and so on. So I don't think that copying everything under the EN directory to a ES directory and translating would be a good idea. So, what do you think would be the best approach?

For example in `ENTimeExpressionParser.js` the only thing that would be changed would be `noon = mediodía`, `midnight = medianoche`.

Any suggestion?

**Comment by penne12** [comment]
Should be as simple as translation - you can look on the readme.md to see how the parsers work, and add them - I'd create a new branch and sent a poll request when you're done.

**Comment by wanasit** [comment]
Hi @gimenete sorry for my slow response.

I afraid that copying EN directory to ES directory is still the best way in my opinion. I know there will be a lot of duplication.

I also agree with @penne12. Normally, it won't be easy as translate keywords. You may need a lot of additional hacks. So having the language specific parsers and refiners are more recommended.

After we see the patterns in 2-3 languages and very confident, maybe we will refactor them later and create a shared abstract code. But, currently, we have only two (maybe three, if include ES), it is too early to do that.
