### ISSUE TITLE
Configurable Time Keywords

### ISSUE THREAD

**Issue by penne12** [wanasit/chrono#87]
In response to #86:

Make the words used for matching time in the casual date parser configurable (use tom for tomorrow, for ytd for yesterday).

Is it ok if I implement this, @wanasit?

**Comment by wanasit** [comment]
"tom" is not a common abbreviation for "tomorrow". I prefer not to include things that are not common. And I think supporting configurable keywords doesn't worth its complication.

But if you want to try the idea and believe you can make it easy to use, I will be very interested to see your change.

**Comment by penne12** [comment]
Ok - I'll send a PR.
