### ISSUE TITLE
"Febuary" and impossible dates

### ISSUE THREAD

**Issue by gimenete** [wanasit/chrono#94]
In the `test_en_little_endian.js` I see these tests:

```js
var text = "29 Febuary 2014";
var results = chrono.strict.parse(text, new Date(2012,7,10));
ok(results.length == 0, JSON.stringify( results ))

var text = "29 Febuary";
var results = chrono.strict.parse(text, new Date(2012,7,10));
ok(results.length == 0, JSON.stringify( results ))
```

I think these tests are meant to not be parsed because those months don't have that number of days because there are other two tests testing months of 32 days. But I believe that in these two tests it is not parsing the date not because of those months not having 29 days but because "Febuary" is spelled without an "r".

**Comment by wanasit** [comment]
You are right. I fixed the typo.
1eb3903
