### ISSUE TITLE
Should it handle short years before 2000?

### ISSUE THREAD

**Issue by philgooch** [wanasit/chrono#97]
`chrono.parseDate('1/12/99')`

returns

`Wed Jan 12 2056 12:00:00 GMT+0000 (GMT)`

Just wondering if there should be a cutoff for handling 20th century short years, and if so, what should it be?

**Comment by penne12** [comment]
`2056 ` hmm... looks like your computer is 32 bit? Chrono should be able to handle 2099.

I don't think this is useful for the majority of use case, but if you'd like to implement this as a configurable option, I'd love to see a PR.

**Comment by philgooch** [comment]
I think the issue is on lines 

https://github.com/wanasit/chrono/blob/master/src/parsers/EN/ENSlashDateFormatParser.js#L95

`year = year + 2500 - 543`

So if year is `99` then we'll get `2056` as the result.

I'll familiarise myself more with the code and work on a configurable option, e.g. the ability to choose which century a short year refers to if it is greater than the two-digit current year.
